In [21]:
# Import & configs
import requests
import time
import json
import logging
import pandas as pd
from datetime import datetime, timedelta, timezone
from pathlib import Path
from google.cloud import storage

# ── GCP config ────────────────────────────────────────────────
GCP_PROJECT   = "vuthesis-llm-buzz"
GCS_BUCKET    = "thesis-bucket-vua"
BRONZE_PREFIX = "bronze/reddit"

# ── Scraper config ────────────────────────────────────────────
PRE_LAUNCH_DAYS   = 90        # window before launch date
POSTS_PER_REQUEST = 100       # Reddit max per call
SLEEP_BETWEEN_REQUESTS = 2    # seconds — respect rate limits
SLEEP_BETWEEN_EVENTS   = 10   # seconds — pause between products
MIN_POST_THRESHOLD = 500      # warn if event falls below this

# ── Paths ─────────────────────────────────────────────────────
EVENTS_PATH     = Path(r"C:\Users\User\Desktop\VU\Thesis\Code\LLM-prelaunch-buzz-postlaunch-predictor\events.csv")
CHECKPOINT_PATH = Path("checkpoint.json")
CACHE_DIR       = Path("data/cache")
CACHE_DIR.mkdir(parents=True, exist_ok=True)

# ── Logging ───────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("reddit_scraper.log", encoding="utf-8")
    ]
)
log = logging.getLogger(__name__)

# ── Headers — browser-like UA avoids 429 blocks ───────────────
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36",
    "Accept": "application/json",
}

log.info("Config loaded")

2026-05-18 16:14:22,493 [INFO] Config loaded

In [22]:
events = pd.read_csv(EVENTS_PATH, encoding="utf-8")
events.columns = events.columns.str.strip()
events["launch_date"] = pd.to_datetime(
    events["launch_date"].str.strip(), dayfirst=True, utc=True
)
events["subreddits_list"] = [[] for _ in range(len(events))]

print(f"Loaded {len(events)} events:")
print("Columns:", events.columns.tolist())
display(events[["product_name", "launch_date", "product_type"]])

Loaded 35 events:
Columns: ['product_name', 'brand', 'launch_date', 'product_type', 'pre_launch_subreddits', 'subreddits_list']

                product_name               launch_date product_type
0          Fire HD 10 (2019) 2019-10-30 00:00:00+00:00  Utilitarian
1          Fire HD 8 (2020)  2020-09-30 00:00:00+00:00  Utilitarian
2             Fire 7 (2019)  2019-05-29 00:00:00+00:00  Utilitarian
3             iPad Pro 2020  2020-03-25 00:00:00+00:00      Hedonic
4          iPad Air 2 (2014) 2014-10-16 00:00:00+00:00      Hedonic
5            MacBook Air M1  2020-11-17 00:00:00+00:00      Hedonic
6                iPad mini 6 2021-09-24 00:00:00+00:00      Hedonic
7            MacBook Pro 16" 2021-06-10 00:00:00+00:00      Hedonic
8                 Galaxy S23 2023-02-17 00:00:00+00:00  Utilitarian
9                    Pixel 5 2020-10-15 00:00:00+00:00  Utilitarian
10                 iPhone 14 2022-09-16 00:00:00+00:00      Hedonic
11                 iPhone 15 2023-09-22 00:00:00+00:00      Hedonic
12                Galaxy S22 2022-02-25 00:00:00+00:00  Utilitarian
13                   Pixel 7 2022-10-13 00:00:00+00:00  Utilitarian
14                 iPhone 13 2021-09-24 00:00:00+00:00      Hedonic
15                Galaxy S21 2021-01-29 00:00:00+00:00      Hedonic
16                   Pixel 6 2021-10-28 00:00:00+00:00      Hedonic
17            MacBook Air M2 2022-07-15 00:00:00+00:00  Utilitarian
18                 iPad Pro  2022-10-26 00:00:00+00:00  Utilitarian
19         Samsung Galaxy S4 2013-04-27 00:00:00+00:00      Hedonic
20         Samsung Galaxy S5 2014-04-11 00:00:00+00:00      Hedonic
21         Samsung Galaxy S6 2015-04-10 00:00:00+00:00      Hedonic
22    Samsung Galaxy S7 Edge 2016-03-11 00:00:00+00:00      Hedonic
23         Samsung Galaxy S8 2017-04-21 00:00:00+00:00      Hedonic
24     Samsung Galaxy S20 FE 2020-10-02 00:00:00+00:00      Hedonic
25  Samsung Galaxy S21 Ultra 2021-01-29 00:00:00+00:00      Hedonic
26  Samsung Galaxy S22 Ultra 2022-02-25 00:00:00+00:00      Hedonic
27           Google Pixel 3a 2019-05-07 00:00:00+00:00  Utilitarian
28         Google Pixel 4 XL 2019-10-24 00:00:00+00:00  Utilitarian
29           Google Pixel 4a 2020-08-20 00:00:00+00:00  Utilitarian
30            Moto G 3rd Gen 2015-07-28 00:00:00+00:00  Utilitarian
31           Moto G 4th Gen" 2016-05-17 00:00:00+00:00  Utilitarian
32               Moto G Fast 2020-06-18 00:00:00+00:00  Utilitarian
33         Moto G Power 2022 2022-02-10 00:00:00+00:00  Utilitarian
34                     LG G3 2014-07-18 00:00:00+00:00      Hedonic

In [23]:
# Fix the product name in events DataFrame
for idx, row in events.iterrows():
    if "ipad pro" in row["product_name"].lower() and "m2" not in row["product_name"].lower() and "2020" not in row["product_name"].lower():
        events.at[idx, "product_name"] = "iPad Pro M2"
        events.at[idx, "subreddits_list"] = ["ipad", "iPadPro", "apple", "ios", "tablets", "technology"]
        print(f"Fixed row {idx}: {row['product_name']} -> iPad Pro M2")

Fixed row 18: iPad Pro  -> iPad Pro M2

In [ ]:
overrides = {
    "Fire HD 10":  ["kindlefire", "amazonecho", "amazon", "tablets",
                    "android", "gadgets", "technology"],
    "Fire HD 8":   ["kindlefire", "amazonecho", "amazon", "tablets",
                    "android", "gadgets", "technology"],
    "Fire 7":      ["kindlefire", "tablets", "android", "gadgets"],
    "iPad Pro 2020":  ["ipad", "iPadPro", "apple", "technology", "gadgets"],
    "iPad Air 2":     ["ipad", "apple", "technology", "gadgets"],
    "MacBook Air M1": ["apple", "mac", "macbook", "applesilicon", "technology", "laptops"],
    "iPad mini 6":    ["ipad", "iPadmini", "apple", "ios", "tablets", "technology"],
    "MacBook Pro 16": ["apple", "mac", "macbook", "applesilicon", "technology", "laptops"],
    "Galaxy S23":     ["GalaxyS23", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Pixel 5":        ["GooglePixel", "pixel5", "android", "technology", "gadgets"],
    "iPhone 14":      ["iphone", "apple", "ios", "technology", "gadgets", "smartphones"],
    "iPhone 15":      ["iphone", "apple", "ios", "technology", "gadgets", "smartphones"],
    "Galaxy S22":     ["GalaxyS22", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Pixel 7":        ["GooglePixel", "pixel7", "android", "technology", "gadgets", "smartphones"],
    "iPhone 13":      ["iphone", "apple", "ios", "technology", "gadgets", "smartphones"],
    "Galaxy S21":     ["GalaxyS21", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Pixel 6":        ["GooglePixel", "pixel6", "android", "technology", "gadgets"],
    "MacBook Air M2": ["apple", "mac", "macbook", "MacOS", "technology", "laptops"],
    "iPad Pro M2":    ["ipad", "iPadPro", "apple", "ios", "tablets", "technology"],
    "iPad Pro ":      ["ipad", "iPadPro", "apple", "ios", "tablets", "technology"],

    # Samsung Galaxy S series
    "Samsung Galaxy S4":       ["galaxys4", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S5":       ["galaxys5", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S6":       ["GalaxyS6", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S7 Edge":  ["GalaxyS7", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S8":       ["GalaxyS8", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S20 FE":   ["GalaxyS20FE", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S21 Ultra":["GalaxyS21", "samsung", "android", "technology", "gadgets", "smartphones"],
    "Samsung Galaxy S22 Ultra":["GalaxyS22", "samsung", "android", "technology", "gadgets", "smartphones"],

    # Google Pixel
    "Google Pixel 3a": ["GooglePixel", "pixel3a", "android", "technology", "gadgets", "smartphones"],
    "Google Pixel 4 XL": ["GooglePixel", "pixel4", "android", "technology", "gadgets", "smartphones"],
    "Google Pixel 4a": ["GooglePixel", "pixel4a", "android", "technology", "gadgets", "smartphones"],

    # Moto
    "Moto G 3rd Gen":   ["motorola", "android", "moto", "technology", "gadgets", "smartphones"],
    "Moto G 4th Gen":   ["motorola", "android", "moto", "technology", "gadgets", "smartphones"],
    "Moto G Fast":      ["motorola", "android", "moto", "technology", "gadgets", "smartphones"],
    "Moto G Power 2022":["motorola", "android", "moto", "technology", "gadgets", "smartphones"],

    # LG
    "LG G3": ["lgg3", "android", "technology", "gadgets", "smartphones"],


for product, subs in overrides.items():
    for idx, row in events.iterrows():
        if product.lower().strip() in row["product_name"].lower():
            events.at[idx, "subreddits_list"] = subs
            break

print("Subreddit assignment:")
for _, row in events.iterrows():
    print(f"  {row['product_name']}: {len(row['subreddits_list'])} subreddits — {row['subreddits_list']}")

Subreddit assignment:
  Fire HD 10 (2019): 7 subreddits — ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
  Fire HD 8 (2020) : 7 subreddits — ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
  Fire 7 (2019) : 4 subreddits — ['kindlefire', 'tablets', 'android', 'gadgets']
  iPad Pro 2020 : 6 subreddits — ['ipad', 'iPadPro', 'apple', 'ios', 'tablets', 'technology']
  iPad Air 2 (2014): 4 subreddits — ['ipad', 'apple', 'technology', 'gadgets']
  MacBook Air M1 : 6 subreddits — ['apple', 'mac', 'macbook', 'applesilicon', 'technology', 'laptops']
  iPad mini 6: 6 subreddits — ['ipad', 'iPadmini', 'apple', 'ios', 'tablets', 'technology']
  MacBook Pro 16": 6 subreddits — ['apple', 'mac', 'macbook', 'applesilicon', 'technology', 'laptops']
  Galaxy S23: 6 subreddits — ['GalaxyS23', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Pixel 5: 5 subreddits — ['GooglePixel', 'pixel5', 'android', 'technology', 'gadgets']
  iPhone 14: 6 subreddits — ['iphone', 'apple', 'ios', 'technology', 'gadgets', 'smartphones']
  iPhone 15: 6 subreddits — ['iphone', 'apple', 'ios', 'technology', 'gadgets', 'smartphones']
  Galaxy S22: 6 subreddits — ['GalaxyS22', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Pixel 7: 6 subreddits — ['GooglePixel', 'pixel7', 'android', 'technology', 'gadgets', 'smartphones']
  iPhone 13: 6 subreddits — ['iphone', 'apple', 'ios', 'technology', 'gadgets', 'smartphones']
  Galaxy S21: 6 subreddits — ['GalaxyS21', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Pixel 6: 5 subreddits — ['GooglePixel', 'pixel6', 'android', 'technology', 'gadgets']
  MacBook Air M2: 6 subreddits — ['apple', 'mac', 'macbook', 'MacOS', 'technology', 'laptops']
  iPad Pro M2: 6 subreddits — ['ipad', 'iPadPro', 'apple', 'ios', 'tablets', 'technology']
  Samsung Galaxy S4: 6 subreddits — ['galaxys4', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S5: 6 subreddits — ['galaxys5', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S6: 6 subreddits — ['GalaxyS6', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S7 Edge: 6 subreddits — ['GalaxyS7', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S8: 6 subreddits — ['GalaxyS8', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S20 FE: 6 subreddits — ['GalaxyS20FE', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S21 Ultra: 6 subreddits — ['GalaxyS21', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Samsung Galaxy S22 Ultra: 6 subreddits — ['GalaxyS22', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
  Google Pixel 3a: 6 subreddits — ['GooglePixel', 'pixel3a', 'android', 'technology', 'gadgets', 'smartphones']
  Google Pixel 4 XL: 6 subreddits — ['GooglePixel', 'pixel4', 'android', 'technology', 'gadgets', 'smartphones']
  Google Pixel 4a: 6 subreddits — ['GooglePixel', 'pixel4a', 'android', 'technology', 'gadgets', 'smartphones']
  Moto G 3rd Gen: 6 subreddits — ['motorola', 'android', 'moto', 'technology', 'gadgets', 'smartphones']
  Moto G 4th Gen": 6 subreddits — ['motorola', 'android', 'moto', 'technology', 'gadgets', 'smartphones']
  Moto G Fast: 6 subreddits — ['motorola', 'android', 'moto', 'technology', 'gadgets', 'smartphones']
  Moto G Power 2022: 6 subreddits — ['motorola', 'android', 'moto', 'technology', 'gadgets', 'smartphones']
  LG G3: 5 subreddits — ['lgg3', 'android', 'technology', 'gadgets', 'smartphones']

In [26]:
#Checkpoint helpers - helps track which events are fully scrapped 
# so it can be resumed if interrupted
def load_checkpoint() -> dict:
    if CHECKPOINT_PATH.exists():
        with open(CHECKPOINT_PATH) as f:
            return json.load(f)
    return {}

def save_checkpoint(checkpoint: dict):
    with open(CHECKPOINT_PATH, "w") as f:
        json.dump(checkpoint, f, indent=2)

def mark_complete(checkpoint: dict, event_key: str, post_count: int):
    checkpoint[event_key] = {
        "status": "complete",
        "post_count": post_count,
        "completed_at": datetime.utcnow().isoformat()
    }
    save_checkpoint(checkpoint)

checkpoint = load_checkpoint()
print(f"Checkpoint loaded — {len(checkpoint)} events already completed:")
for k, v in checkpoint.items():
    print(f"  {k}: {v['post_count']} posts ({v['completed_at']})")

Checkpoint loaded — 19 events already completed:
  galaxy_s23: 984 posts (2026-05-08T12:52:50.135549)
  iphone_15: 670 posts (2026-05-08T13:02:33.114515)
  pixel_7: 751 posts (2026-05-08T13:12:40.701465)
  ipad_pro_2020_: 2834 posts (2026-05-11T12:20:30.971554)
  macbook_air_m1: 1307 posts (2026-05-11T12:21:38.902835)
  ipad_mini_6: 1007 posts (2026-05-11T12:22:30.712038)
  iphone_14: 15186 posts (2026-05-11T12:37:01.315668)
  iphone_13: 9561 posts (2026-05-11T12:42:42.529582)
  galaxy_s21: 4079 posts (2026-05-11T12:45:50.475036)
  pixel_6: 40470 posts (2026-05-11T13:08:42.625164)
  macbook_air_m2: 3410 posts (2026-05-11T13:11:03.398158)
  fire_7_(2019)_: 5 posts (2026-05-12T15:45:54.316860)
  ipad_air_2_(2014): 5 posts (2026-05-12T15:46:13.165740)
  macbook_air_m1_: 1061 posts (2026-05-12T15:47:32.006522)
  macbook_pro_16": 1026 posts (2026-05-12T15:49:21.705679)
  pixel_5: 21112 posts (2026-05-12T16:07:20.281323)
  ipad_pro_m2: 1598 posts (2026-05-12T16:08:31.815997)
  fire_hd_10_(2019): 227 posts (2026-05-13T00:02:15.831061)
  fire_hd_8_(2020): 455 posts (2026-05-13T00:03:26.203240)

In [27]:
# Core scrapping functions
def fetch_posts_page(subreddit: str, query: str, after: str = None) -> dict | None:
    """Fetch one page (up to 100 posts) from Reddit search JSON endpoint."""
    url = f"https://www.reddit.com/r/{subreddit}/search.json"
    params = {
        "q":           query,
        "restrict_sr": 1,
        "sort":        "new",
        "t":           "all",
        "limit":       POSTS_PER_REQUEST,
    }
    if after:
        params["after"] = after

    try:
        resp = requests.get(url, headers=HEADERS, params=params, timeout=15)
        if resp.status_code == 429:
            log.warning("Rate limited — sleeping 60s")
            time.sleep(60)
            return fetch_posts_page(subreddit, query, after)  # retry once
        if resp.status_code != 200:
            log.error(f"HTTP {resp.status_code} for r/{subreddit} query='{query}'")
            return None
        return resp.json()["data"]
    except Exception as e:
        log.error(f"Request error: {e}")
        return None


def fetch_top_comments(subreddit: str, post_id: str) -> list[dict]:
    """Fetch top-level comments for a single post."""
    url = f"https://www.reddit.com/r/{subreddit}/comments/{post_id}.json"
    try:
        resp = requests.get(url, headers=HEADERS, timeout=15)
        if resp.status_code != 200:
            return []
        data = resp.json()
        # data[1] contains comment listing
        comments = data[1]["data"]["children"]
        return [
            c["data"] for c in comments
            if c["kind"] == "t1"  # t1 = comment
            and not c["data"].get("body") in ["[deleted]", "[removed]", None]
        ]
    except Exception as e:
        log.warning(f"Could not fetch comments for {post_id}: {e}")
        return []


def parse_post(raw: dict, product_event: str, launch_ts: float) -> dict | None:
    """Extract relevant fields from a raw Reddit post dict."""
    body = raw.get("selftext", "") or ""
    title = raw.get("title", "") or ""

    # Skip deleted/removed
    if body in ["[deleted]", "[removed]"] or not title:
        return None

    created_utc = raw.get("created_utc", 0)
    days_to_launch = (launch_ts - created_utc) / 86400  # positive = before launch

    return {
        "post_id":       raw.get("id"),
        "product_event": product_event,
        "subreddit":     raw.get("subreddit"),
        "title":         title,
        "body_text":     body,
        "upvotes":       raw.get("score", 0),
        "num_comments":  raw.get("num_comments", 0),
        "created_utc":   created_utc,
        "days_to_launch": round(days_to_launch, 2),
        "url":           f"https://reddit.com{raw.get('permalink', '')}",
        "type":          "post",
    }


def parse_comment(raw: dict, product_event: str, post_id: str,
                  subreddit: str, launch_ts: float) -> dict | None:
    """Extract relevant fields from a raw Reddit comment dict."""
    body = raw.get("body", "") or ""
    if body in ["[deleted]", "[removed]"] or not body.strip():
        return None

    created_utc = raw.get("created_utc", 0)
    days_to_launch = (launch_ts - created_utc) / 86400

    return {
        "post_id":        f"comment_{raw.get('id')}",
        "parent_post_id": post_id,
        "product_event":  product_event,
        "subreddit":      subreddit,
        "title":          "",
        "body_text":      body,
        "upvotes":        raw.get("score", 0),
        "num_comments":   0,
        "created_utc":    created_utc,
        "days_to_launch": round(days_to_launch, 2),
        "url":            f"https://reddit.com{raw.get('permalink', '')}",
        "type":           "comment",
    }

log.info("Core functions defined")

2026-05-18 16:17:53,764 [INFO] Core functions defined

In [28]:
# GCS Upload helper
gcs_client = storage.Client(project=GCP_PROJECT)
gcs_bucket = gcs_client.bucket(GCS_BUCKET)

def upload_batch_to_gcs(records: list[dict], product_event: str) -> str:
    """Upload a list of records as a JSONL file to GCS Bronze.
    Returns the GCS path of the uploaded file.
    """
    if not records:
        return ""

    timestamp = int(time.time())
    gcs_path = f"{BRONZE_PREFIX}/{product_event}/{timestamp}.jsonl"
    blob = gcs_bucket.blob(gcs_path)

    jsonl_content = "\n".join(json.dumps(r) for r in records)

    blob.upload_from_string(
        jsonl_content,
        content_type="application/jsonl",
        retry=storage.retry.DEFAULT_RETRY  # resumable — survives drops
    )
    log.info(f"  Uploaded {len(records)} records → gs://{GCS_BUCKET}/{gcs_path}")
    return gcs_path


def upload_events_csv():
    """Back up events.csv to GCS config folder."""
    blob = gcs_bucket.blob("config/events.csv")
    blob.upload_from_filename(str(EVENTS_PATH))
    log.info("events.csv backed up to gs://config/events.csv")

upload_events_csv()
log.info("GCS client ready")

2026-05-18 16:18:03,500 [INFO] events.csv backed up to gs://config/events.csv
2026-05-18 16:18:03,502 [INFO] GCS client ready

In [30]:
#Single event scrapper
def scrape_event(row: pd.Series, fetch_comments: bool = True,
                 batch_size: int = 200) -> int:
    """
    Scrape all pre-launch posts (and optionally comments) for one product event.
    Uploads in batches of `batch_size` records to GCS.
    Returns total number of records collected.
    """
    product_event = row["product_name"].lower().replace(" ", "_")
    launch_dt     = row["launch_date"]
    launch_ts     = launch_dt.timestamp()
    window_start  = launch_dt - timedelta(days=PRE_LAUNCH_DAYS)
    window_start_ts = window_start.timestamp()
    subreddits    = row["subreddits_list"]
    query         = row["product_name"]  # use product name as search query

    log.info(f"\n{'='*60}")
    log.info(f"Scraping: {product_event}")
    log.info(f"Window: {window_start.date()} → {launch_dt.date()}")
    log.info(f"Subreddits: {subreddits}")

    all_records = []
    seen_post_ids = set()
    total_uploaded = 0

    for subreddit in subreddits:
        log.info(f"  → r/{subreddit}")
        after = None
        sub_post_count = 0
        out_of_window = False

        while not out_of_window:
            page = fetch_posts_page(subreddit, query, after)
            if not page or not page.get("children"):
                break

            for child in page["children"]:
                if child["kind"] != "t3":  # t3 = post
                    continue
                raw = child["data"]
                created_utc = raw.get("created_utc", 0)

                # Stop if we've gone past the 90-day window
                if created_utc < window_start_ts:
                    out_of_window = True
                    break

                # Skip if post is after launch date
                if created_utc >= launch_ts:
                    continue

                post_id = raw.get("id")
                if post_id in seen_post_ids:
                    continue
                seen_post_ids.add(post_id)

                parsed = parse_post(raw, product_event, launch_ts)
                if parsed:
                    all_records.append(parsed)
                    sub_post_count += 1

                    # Fetch top-level comments for this post
                    if fetch_comments and raw.get("num_comments", 0) > 0:
                        time.sleep(0.5)  # brief pause before comment fetch
                        comments = fetch_top_comments(subreddit, post_id)
                        for c in comments:
                            parsed_c = parse_comment(
                                c, product_event, post_id, subreddit, launch_ts
                            )
                            if parsed_c:
                                all_records.append(parsed_c)

                # Upload in batches to avoid memory buildup
                if len(all_records) >= batch_size:
                    upload_batch_to_gcs(all_records, product_event)
                    total_uploaded += len(all_records)
                    all_records = []

            after = page.get("after")
            if not after:
                break

            time.sleep(SLEEP_BETWEEN_REQUESTS)

        log.info(f"     r/{subreddit}: {sub_post_count} posts in window")

    # Upload any remaining records
    if all_records:
        upload_batch_to_gcs(all_records, product_event)
        total_uploaded += len(all_records)

    log.info(f"  TOTAL records uploaded for {product_event}: {total_uploaded}")
    if total_uploaded < MIN_POST_THRESHOLD:
        log.warning(
            f"  ⚠ {product_event} has {total_uploaded} records — "
            f"below minimum threshold of {MIN_POST_THRESHOLD}. "
            f"Consider adding more subreddits or broadening the search query."
        )

    return total_uploaded

log.info("scrape_event() defined")

2026-05-18 16:19:29,256 [INFO] scrape_event() defined

In [87]:
# Cell 6b - Arctic Shift scraper with multi-query support
def scrape_event_arctic_shift(row, fetch_comments=True):
    product_event  = row["product_name"].lower().replace(" ", "_")
    launch_dt      = row["launch_date"]
    window_start   = launch_dt - timedelta(days=PRE_LAUNCH_DAYS)
    subreddits     = row["subreddits_list"]

    # Support single string or list of queries
    raw_query = row.get("query_list", row["product_name"])
    queries   = raw_query if isinstance(raw_query, list) else [raw_query]

    after_ts  = int(window_start.timestamp())
    before_ts = int(launch_dt.timestamp())
    after_str = window_start.strftime("%Y-%m-%d")

    log.info(f"\n{'='*60}")
    log.info(f"Scraping (Arctic Shift): {product_event}")
    log.info(f"Window: {window_start.date()} to {launch_dt.date()}")
    log.info(f"Queries: {queries}")
    log.info(f"Subreddits: {subreddits}")

    seen_post_ids = set()  # dedup across all queries + subreddits
    total_uploaded = 0

    for query in queries:
        log.info(f"\n  Query: '{query}'")
        query_records = []

        for subreddit in subreddits:
            log.info(f"  -> r/{subreddit}")
            sub_post_count = 0
            before_str_cur = launch_dt.strftime("%Y-%m-%d")

            while True:
                url = "https://arctic-shift.photon-reddit.com/api/posts/search"
                params = {
                    "subreddit": subreddit,
                    "title":     query,
                    "after":     after_str,
                    "before":    before_str_cur,
                    "limit":     100,
                    "sort":      "desc",
                }

                try:
                    resp = requests.get(url, headers=HEADERS, params=params, timeout=30)
                    if resp.status_code in (429, 422):
                        wait = 60 if resp.status_code == 422 else 30
                        log.warning(f"Rate limited ({resp.status_code}) -- sleeping {wait}s")
                        time.sleep(wait)
                        continue
                    if resp.status_code != 200:
                        log.error(f"HTTP {resp.status_code}: {resp.text[:200]}")
                        break
                    posts = resp.json().get("data", [])
                except Exception as e:
                    log.error(f"Request error: {e}")
                    break

                if not posts:
                    break

                for post in posts:
                    post_id = post.get("id")
                    if not post_id or post_id in seen_post_ids:
                        continue
                    seen_post_ids.add(post_id)

                    parsed = {
                        "post_id":        post_id,
                        "product_event":  product_event,
                        "subreddit":      post.get("subreddit"),
                        "title":          post.get("title", ""),
                        "body_text":      post.get("selftext", ""),
                        "upvotes":        post.get("score", 0),
                        "num_comments":   post.get("num_comments", 0),
                        "created_utc":    post.get("created_utc"),
                        "days_to_launch": round(
                            (before_ts - int(post.get("created_utc", before_ts))) / 86400, 2
                        ),
                        "url":            f"https://reddit.com{post.get('permalink', '')}",
                        "type":           "post",
                        "query_matched":  query,
                    }

                    if parsed["body_text"] in ["[deleted]", "[removed]"] and not parsed["title"]:
                        continue

                    query_records.append(parsed)
                    sub_post_count += 1

                    if sub_post_count % 100 == 0:
                        log.info(f"     ... {sub_post_count} posts so far in r/{subreddit}")

                    # Fetch top-level comments
                    if fetch_comments and parsed["num_comments"] > 0:
                        time.sleep(0.5)
                        try:
                            c_resp = requests.get(
                                "https://arctic-shift.photon-reddit.com/api/comments/search",
                                headers=HEADERS,
                                params={"link_id": f"t3_{post_id}", "limit": 100},
                                timeout=30
                            )
                            if c_resp.status_code == 200:
                                for c in c_resp.json().get("data", []):
                                    body = c.get("body", "")
                                    if body in ["[deleted]", "[removed]", ""]:
                                        continue
                                    c_id = c.get("id")
                                    if c_id and c_id not in seen_post_ids:
                                        seen_post_ids.add(c_id)
                                        query_records.append({
                                            "post_id":        f"comment_{c_id}",
                                            "parent_post_id": post_id,
                                            "product_event":  product_event,
                                            "subreddit":      subreddit,
                                            "title":          "",
                                            "body_text":      body,
                                            "upvotes":        c.get("score", 0),
                                            "num_comments":   0,
                                            "created_utc":    c.get("created_utc"),
                                            "days_to_launch": round(
                                                (before_ts - int(c.get("created_utc", before_ts))) / 86400, 2
                                            ),
                                            "url":           f"https://reddit.com{c.get('permalink', '')}",
                                            "type":          "comment",
                                            "query_matched": query,
                                        })
                        except Exception as e:
                            log.warning(f"Comment fetch failed for {post_id}: {e}")

                # Paginate: move before_str_cur to oldest post timestamp
                if len(posts) < 100:
                    break
                oldest_ts = min(int(p.get("created_utc", before_ts)) for p in posts)
                before_str_cur = datetime.utcfromtimestamp(oldest_ts).strftime("%Y-%m-%dT%H:%M:%S")
                time.sleep(2)  # pause between pages

            log.info(f"     r/{subreddit}: {sub_post_count} new posts")
            time.sleep(2)  # pause between subreddits

        # Upload all records for this query
        if query_records:
            upload_batch_to_gcs(query_records, product_event)
            total_uploaded += len(query_records)
            log.info(f"  Uploaded {len(query_records)} records for query '{query}' -- total: {total_uploaded}")

        time.sleep(5)  # pause between queries

    log.info(f"\n  TOTAL: {total_uploaded} records for {product_event}")
    if total_uploaded < MIN_POST_THRESHOLD:
        log.warning(f"  WARNING: {total_uploaded} below threshold of {MIN_POST_THRESHOLD}")

    return total_uploaded

log.info("scrape_event_arctic_shift() defined")

2026-05-23 18:11:12,589 [INFO] scrape_event_arctic_shift() defined

In [17]:
# Run single event (testing)
test_event = events.iloc[0]
print(f"Test event: {test_event['product_name']} (launch: {test_event['launch_date'].date()})")
print(f"Subreddits: {test_event['pre_launch_subreddits']}")
print()

# Run with comments=False for a quick smoke test first
count = scrape_event(test_event, fetch_comments=True)
print(f"\n✓ Test complete — {count} records uploaded to GCS")

2026-05-07 14:56:33,962 [INFO]
============================================================
2026-05-07 14:56:33,963 [INFO] Scraping: fire_hd_10_(2019)
2026-05-07 14:56:33,964 [INFO] Window: 2019-08-01 → 2019-10-30
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 50: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3123, in run_cell
    result = self._run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3178, in _run_cell
    result = runner(coro)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3400, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3641, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\173129886.py", line 8, in <module>
    count = scrape_event(test_event, fetch_comments=True)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\1296763727.py", line 19, in scrape_event
    log.info(f"Window: {window_start.date()} → {launch_dt.date()}")
Message: 'Window: 2019-08-01 → 2019-10-30'
Arguments: ()
2026-05-07 14:56:33,967 [INFO] Subreddits: ['kindlefire', 'tablets', 'android', 'gadgets']
2026-05-07 14:56:33,967 [INFO]   → r/kindlefire

Test event: Fire HD 10 (2019) (launch: 2019-10-30)
Subreddits: r/kindlefire, r/tablets, r/android, r/gadgets

--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3123, in run_cell
    result = self._run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3178, in _run_cell
    result = runner(coro)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3400, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3641, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\173129886.py", line 8, in <module>
    count = scrape_event(test_event, fetch_comments=True)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\1296763727.py", line 27, in scrape_event
    log.info(f"  → r/{subreddit}")
Message: '  → r/kindlefire'
Arguments: ()
2026-05-07 14:56:38,912 [INFO]      r/kindlefire: 1 posts in window
2026-05-07 14:56:38,913 [INFO]   → r/tablets
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3123, in run_cell
    result = self._run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3178, in _run_cell
    result = runner(coro)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3400, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3641, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\173129886.py", line 8, in <module>
    count = scrape_event(test_event, fetch_comments=True)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\1296763727.py", line 27, in scrape_event
    log.info(f"  → r/{subreddit}")
Message: '  → r/tablets'
Arguments: ()
2026-05-07 14:56:39,569 [INFO]      r/tablets: 0 posts in window
2026-05-07 14:56:39,570 [INFO]   → r/android
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3123, in run_cell
    result = self._run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3178, in _run_cell
    result = runner(coro)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3400, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3641, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\173129886.py", line 8, in <module>
    count = scrape_event(test_event, fetch_comments=True)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\1296763727.py", line 27, in scrape_event
    log.info(f"  → r/{subreddit}")
Message: '  → r/android'
Arguments: ()
2026-05-07 14:56:40,102 [INFO]      r/android: 0 posts in window
2026-05-07 14:56:40,102 [INFO]   → r/gadgets
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content

✓ Test complete — 8 records uploaded to GCS

--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u26a0' in position 36: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3123, in run_cell
    result = self._run_cell(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3178, in _run_cell
    result = runner(coro)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3400, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3641, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\173129886.py", line 8, in <module>
    count = scrape_event(test_event, fetch_comments=True)
  File "C:\Users\User\AppData\Local\Temp\ipykernel_7440\1296763727.py", line 94, in scrape_event
    log.warning(
Message: '  ⚠ fire_hd_10_(2019) has 8 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.'
Arguments: ()

In [44]:
# ⚠ Run once to clear all checkpoint data — do not re-run
save_checkpoint({})
print("✓ Checkpoint cleared")

✓ Checkpoint cleared

In [31]:
# Override subreddits for underperforming events
fixes = {
    "iPhone 14": {
        "subreddits": ["iphone", "apple", "ios", "AppleWatch", 
                       "technology", "gadgets", "smartphones"],
        "query": "iPhone 14"
    },
    "Galaxy S22": {
        "subreddits": ["GalaxyS22", "samsung", "android", "GooglePixel",
                       "technology", "gadgets", "smartphones"],
        "query": "Galaxy S22"
    },
    "iPad mini 6": {
        "subreddits": ["ipad", "apple", "ios", "tablets", 
                       "gadgets", "technology"],
        "query": "iPad mini 6"
    },
    "MacBook Air M1": {
        "subreddits": ["apple", "mac", "macbook", "MacOS",
                       "technology", "gadgets", "laptops"],
        "query": "MacBook Air M1"
    },
    "Pixel 7": {
        "subreddits": ["GooglePixel", "pixel7", "android",
                       "technology", "gadgets", "smartphones"],
        "query": "Pixel 7"
    },
    "Pixel 5": {
        "subreddits": ["GooglePixel", "android", "technology", 
                       "gadgets", "smartphones"],
        "query": "Pixel 5"
    },
    "Galaxy S23": {
        "subreddits": ["GalaxyS23", "samsung", "android",
                       "technology", "gadgets", "smartphones"],
        "query": "Galaxy S23"
    },
    "iPhone 15": {
        "subreddits": ["iphone", "apple", "ios",
                       "technology", "gadgets", "smartphones"],
        "query": "iPhone 15"
    },
}

for product, config in fixes.items():
    mask = events["product_name"].str.contains(product, case=False)
    if mask.any():
        idx = events[mask].index[0]
        events.at[idx, "subreddits_list"] = config["subreddits"]
        events.at[idx, "product_name"] = config["query"]  # cleaner query
        print(f"✓ Fixed: {product}")

# Clear checkpoint for these events so Cell 9 re-scrapes them
checkpoint = load_checkpoint()
to_rerun = ["iphone_14", "galaxy_s22", "ipad_mini_6", "macbook_air_m1_"]
for key in to_rerun:
    if key in checkpoint:
        del checkpoint[key]
        print(f"✓ Cleared checkpoint: {key}")
save_checkpoint(checkpoint)

print("\nReady to re-run pipeline")

✓ Fixed: iPhone 14
✓ Fixed: Galaxy S22
✓ Fixed: iPad mini 6
✓ Fixed: MacBook Air M1
✓ Fixed: Pixel 7
✓ Fixed: Pixel 5
✓ Fixed: Galaxy S23
✓ Fixed: iPhone 15
✓ Cleared checkpoint: iphone_14
✓ Cleared checkpoint: ipad_mini_6
✓ Cleared checkpoint: macbook_air_m1_

Ready to re-run pipeline

In [16]:
# Verify GCS output
def list_bronze_files(product_event: str = None) -> pd.DataFrame:
    """List all files in GCS Bronze, optionally filtered by product event."""
    prefix = f"{BRONZE_PREFIX}/{product_event}/" if product_event else BRONZE_PREFIX
    blobs = list(gcs_bucket.list_blobs(prefix=prefix))

    rows = []
    for b in blobs:
        if b.name.endswith(".jsonl"):
            rows.append({
                "path":    b.name,
                "size_kb": round(b.size / 1024, 1),
                "updated": b.updated
            })

    return pd.DataFrame(rows) if rows else pd.DataFrame(columns=["path", "size_kb", "updated"])


def preview_gcs_file(gcs_path: str, n: int = 5) -> pd.DataFrame:
    """Download and preview the first n records from a GCS JSONL file."""
    blob = gcs_bucket.blob(gcs_path)
    content = blob.download_as_text()
    lines = content.strip().split("\n")[:n]
    return pd.DataFrame([json.loads(l) for l in lines])


# Show what was uploaded for the test event
test_key = events.iloc[0]["product_name"].lower().replace(" ", "_")
files_df = list_bronze_files(test_key)
print(f"Files in GCS for '{test_key}':")
display(files_df)

if not files_df.empty:
    print("\nFirst 3 records:")
    display(preview_gcs_file(files_df.iloc[0]["path"], n=3))

Files in GCS for 'fire_hd_10_(2019)':

,path,size_kb,updated
0,bronze/reddit/fire_hd_10_(2019)/1778157808.jsonl,0.7,2026-05-07 12:43:28.982000+00:00
1,bronze/reddit/fire_hd_10_(2019)/1778158600.jsonl,4.6,2026-05-07 12:56:40.991000+00:00
2,bronze/reddit/fire_hd_10_(2019)/1778158652.jsonl,4.6,2026-05-07 12:57:33.011000+00:00
3,bronze/reddit/fire_hd_10_(2019)/1778167795.jsonl,4.6,2026-05-07 15:29:55.762000+00:00
4,bronze/reddit/fire_hd_10_(2019)/1778179588.jsonl,4.6,2026-05-07 18:46:29.714000+00:00
5,bronze/reddit/fire_hd_10_(2019)/1778182062.jsonl,4.6,2026-05-07 19:27:43.372000+00:00
6,bronze/reddit/fire_hd_10_(2019)/1778240598.jsonl,4.6,2026-05-08 11:43:18.630000+00:00
7,bronze/reddit/fire_hd_10_(2019)/1778244373.jsonl,4.6,2026-05-08 12:46:13.617000+00:00
8,bronze/reddit/fire_hd_10_(2019)/1778600710.jsonl,7.2,2026-05-12 15:45:10.990000+00:00

First 3 records:

,post_id,product_event,subreddit,title,body_text,upvotes,num_comments,created_utc,days_to_launch,url,type
0,cn3td9,fire_hd_10_(2019),kindlefire,Should I wait for a potential 2019 update on f...,"Part of me says to wait, but then again they ""...",8,12,1.565172e+09,83.58,https://reddit.com/r/kindlefire/comments/cn3td...,post

In [26]:
# Re-run iPhone 14 only
checkpoint = load_checkpoint()
del checkpoint["iphone_14"]
save_checkpoint(checkpoint)

In [32]:
#Run full pipeline (all events) - running this only after the single event test passes. Skips already completed events
checkpoint = load_checkpoint()
results = {}

for _, row in events.iterrows():
    event_key = row["product_name"].lower().replace(" ", "_")

    # Skip if already completed
    if event_key in checkpoint and checkpoint[event_key]["status"] == "complete":
        log.info(f"Skipping {event_key} — already in checkpoint")
        results[event_key] = checkpoint[event_key]["post_count"]
        continue

    try:
        count = scrape_event(row, fetch_comments=True)
        results[event_key] = count
        mark_complete(checkpoint, event_key, count)
    except Exception as e:
        log.error(f"Failed on {event_key}: {e}")
        results[event_key] = -1

    time.sleep(SLEEP_BETWEEN_EVENTS)

# Summary
print("\n" + "="*50)
print("SCRAPING COMPLETE — Summary")
print("="*50)
summary = pd.DataFrame([
    {"event": k, "records": v, "threshold_met": v >= MIN_POST_THRESHOLD}
    for k, v in results.items()
])
display(summary)
print(f"\nEvents meeting threshold (≥{MIN_POST_THRESHOLD}): "
      f"{summary['threshold_met'].sum()} / {len(summary)}")

2026-05-18 16:20:12,227 [INFO] Skipping fire_hd_10_(2019) — already in checkpoint
2026-05-18 16:20:12,235 [INFO]
============================================================
2026-05-18 16:20:12,236 [INFO] Scraping: fire_hd_8_(2020)_
2026-05-18 16:20:12,237 [INFO] Window: 2020-07-02 → 2020-09-30
2026-05-18 16:20:12,238 [INFO] Subreddits: ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
2026-05-18 16:20:12,239 [INFO]   → r/kindlefire
2026-05-18 16:20:24,907 [INFO]      r/kindlefire: 11 posts in window
2026-05-18 16:20:24,908 [INFO]   → r/amazonecho
2026-05-18 16:20:25,629 [INFO]      r/amazonecho: 0 posts in window
2026-05-18 16:20:25,630 [INFO]   → r/amazon
2026-05-18 16:20:26,300 [INFO]      r/amazon: 0 posts in window
2026-05-18 16:20:26,302 [INFO]   → r/tablets
2026-05-18 16:20:29,349 [INFO]      r/tablets: 0 posts in window
2026-05-18 16:20:29,350 [INFO]   → r/android
2026-05-18 16:20:31,503 [INFO]      r/android: 1 posts in window
2026-05-18 16:20:31,504 [INFO]   → r/gadgets
2026-05-18 16:20:32,204 [INFO]      r/gadgets: 0 posts in window
2026-05-18 16:20:32,205 [INFO]   → r/technology
2026-05-18 16:20:32,861 [INFO]      r/technology: 0 posts in window
2026-05-18 16:20:32,982 [INFO]   Uploaded 63 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_8_(2020)_/1779114032.jsonl
2026-05-18 16:20:32,983 [INFO]   TOTAL records uploaded for fire_hd_8_(2020)_: 63
2026-05-18 16:20:32,984 [WARNING]   ⚠ fire_hd_8_(2020)_ has 63 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:20:42,987 [INFO] Skipping fire_7_(2019)_ — already in checkpoint
2026-05-18 16:20:42,988 [INFO] Skipping ipad_pro_2020_ — already in checkpoint
2026-05-18 16:20:42,989 [INFO] Skipping ipad_air_2_(2014) — already in checkpoint
2026-05-18 16:20:42,991 [INFO] Skipping macbook_air_m1 — already in checkpoint
2026-05-18 16:20:42,992 [INFO]
============================================================
2026-05-18 16:20:42,993 [INFO] Scraping: ipad_mini_6
2026-05-18 16:20:42,994 [INFO] Window: 2021-06-26 → 2021-09-24
2026-05-18 16:20:42,996 [INFO] Subreddits: ['ipad', 'apple', 'ios', 'tablets', 'gadgets', 'technology']
2026-05-18 16:20:42,997 [INFO]   → r/ipad
2026-05-18 16:20:52,689 [INFO]      r/ipad: 0 posts in window
2026-05-18 16:20:52,690 [INFO]   → r/apple
2026-05-18 16:21:20,325 [INFO]   Uploaded 224 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779114080.jsonl
2026-05-18 16:21:27,699 [INFO]      r/apple: 14 posts in window
2026-05-18 16:21:27,700 [INFO]   → r/ios
2026-05-18 16:21:37,318 [INFO]      r/ios: 0 posts in window
2026-05-18 16:21:37,319 [INFO]   → r/tablets
2026-05-18 16:21:47,084 [INFO]      r/tablets: 0 posts in window
2026-05-18 16:21:47,085 [INFO]   → r/gadgets
2026-05-18 16:21:50,521 [INFO]      r/gadgets: 1 posts in window
2026-05-18 16:21:50,522 [INFO]   → r/technology
2026-05-18 16:21:54,405 [INFO]      r/technology: 1 posts in window
2026-05-18 16:21:54,534 [INFO]   Uploaded 138 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779114114.jsonl
2026-05-18 16:21:54,535 [INFO]   TOTAL records uploaded for ipad_mini_6: 362
2026-05-18 16:21:54,535 [WARNING]   ⚠ ipad_mini_6 has 362 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:22:04,539 [INFO] Skipping macbook_pro_16" — already in checkpoint
2026-05-18 16:22:04,540 [INFO] Skipping galaxy_s23 — already in checkpoint
2026-05-18 16:22:04,541 [INFO] Skipping pixel_5 — already in checkpoint
2026-05-18 16:22:04,543 [INFO]
============================================================
2026-05-18 16:22:04,544 [INFO] Scraping: iphone_14
2026-05-18 16:22:04,545 [INFO] Window: 2022-06-18 → 2022-09-16
2026-05-18 16:22:04,546 [INFO] Subreddits: ['iphone', 'apple', 'ios', 'AppleWatch', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:22:04,547 [INFO]   → r/iphone
2026-05-18 16:22:13,189 [INFO]      r/iphone: 0 posts in window
2026-05-18 16:22:13,190 [INFO]   → r/apple
2026-05-18 16:22:21,517 [INFO]      r/apple: 0 posts in window
2026-05-18 16:22:21,518 [INFO]   → r/ios
2026-05-18 16:22:30,347 [INFO]      r/ios: 0 posts in window
2026-05-18 16:22:30,348 [INFO]   → r/AppleWatch
2026-05-18 16:22:38,943 [INFO]      r/AppleWatch: 0 posts in window
2026-05-18 16:22:38,944 [INFO]   → r/technology
2026-05-18 16:22:50,013 [INFO]      r/technology: 7 posts in window
2026-05-18 16:22:50,014 [INFO]   → r/gadgets
2026-05-18 16:23:02,171 [INFO]   Uploaded 204 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779114182.jsonl
2026-05-18 16:23:05,992 [INFO]      r/gadgets: 7 posts in window
2026-05-18 16:23:05,993 [INFO]   → r/smartphones
2026-05-18 16:23:14,406 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:23:14,508 [INFO]   Uploaded 53 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779114194.jsonl
2026-05-18 16:23:14,509 [INFO]   TOTAL records uploaded for iphone_14: 257
2026-05-18 16:23:14,510 [WARNING]   ⚠ iphone_14 has 257 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:23:24,513 [INFO] Skipping iphone_15 — already in checkpoint
2026-05-18 16:23:24,514 [INFO]
============================================================
2026-05-18 16:23:24,515 [INFO] Scraping: galaxy_s22
2026-05-18 16:23:24,516 [INFO] Window: 2021-11-27 → 2022-02-25
2026-05-18 16:23:24,517 [INFO] Subreddits: ['GalaxyS22', 'samsung', 'android', 'GooglePixel', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:23:24,518 [INFO]   → r/GalaxyS22
2026-05-18 16:23:33,378 [INFO]      r/GalaxyS22: 0 posts in window
2026-05-18 16:23:33,379 [INFO]   → r/samsung
2026-05-18 16:23:41,821 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:23:41,822 [INFO]   → r/android
2026-05-18 16:24:12,074 [INFO]   Uploaded 212 records → gs://thesis-bucket-vua/bronze/reddit/galaxy_s22/1779114251.jsonl
2026-05-18 16:25:13,098 [INFO]      r/android: 72 posts in window
2026-05-18 16:25:13,099 [INFO]   → r/GooglePixel
2026-05-18 16:25:13,660 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:26:14,245 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:27:14,778 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:28:15,318 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:29:15,889 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:30:31,312 [INFO]      r/GooglePixel: 8 posts in window
2026-05-18 16:30:31,313 [INFO]   → r/technology
2026-05-18 16:30:37,659 [INFO]   Uploaded 223 records → gs://thesis-bucket-vua/bronze/reddit/galaxy_s22/1779114637.jsonl
2026-05-18 16:30:38,837 [INFO]      r/technology: 5 posts in window
2026-05-18 16:30:38,838 [INFO]   → r/gadgets
2026-05-18 16:30:40,889 [INFO]      r/gadgets: 1 posts in window
2026-05-18 16:30:40,890 [INFO]   → r/smartphones
2026-05-18 16:30:48,965 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:30:49,065 [INFO]   Uploaded 17 records → gs://thesis-bucket-vua/bronze/reddit/galaxy_s22/1779114648.jsonl
2026-05-18 16:30:49,066 [INFO]   TOTAL records uploaded for galaxy_s22: 452
2026-05-18 16:30:49,067 [WARNING]   ⚠ galaxy_s22 has 452 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:30:59,069 [INFO] Skipping pixel_7 — already in checkpoint
2026-05-18 16:30:59,070 [INFO] Skipping iphone_13 — already in checkpoint
2026-05-18 16:30:59,071 [INFO] Skipping galaxy_s21 — already in checkpoint
2026-05-18 16:30:59,073 [INFO] Skipping pixel_6 — already in checkpoint
2026-05-18 16:30:59,075 [INFO] Skipping macbook_air_m2 — already in checkpoint
2026-05-18 16:30:59,076 [INFO] Skipping ipad_pro_m2 — already in checkpoint
2026-05-18 16:30:59,078 [INFO]
============================================================
2026-05-18 16:30:59,079 [INFO] Scraping: samsung_galaxy_s4
2026-05-18 16:30:59,080 [INFO] Window: 2013-01-27 → 2013-04-27
2026-05-18 16:30:59,081 [INFO] Subreddits: ['galaxys4', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:30:59,082 [INFO]   → r/galaxys4
2026-05-18 16:31:07,230 [INFO]      r/galaxys4: 0 posts in window
2026-05-18 16:31:07,231 [INFO]   → r/samsung
2026-05-18 16:31:16,196 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:31:16,197 [INFO]   → r/android
2026-05-18 16:31:24,472 [INFO]      r/android: 0 posts in window
2026-05-18 16:31:24,473 [INFO]   → r/technology
2026-05-18 16:31:32,998 [INFO]      r/technology: 0 posts in window
2026-05-18 16:31:32,999 [INFO]   → r/gadgets
2026-05-18 16:31:41,217 [INFO]      r/gadgets: 0 posts in window
2026-05-18 16:31:41,218 [INFO]   → r/smartphones
2026-05-18 16:31:49,719 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:31:49,720 [INFO]   TOTAL records uploaded for samsung_galaxy_s4: 0
2026-05-18 16:31:49,721 [WARNING]   ⚠ samsung_galaxy_s4 has 0 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:31:59,725 [INFO]
============================================================
2026-05-18 16:31:59,727 [INFO] Scraping: samsung_galaxy_s5
2026-05-18 16:31:59,730 [INFO] Window: 2014-01-11 → 2014-04-11
2026-05-18 16:31:59,733 [INFO] Subreddits: ['galaxys5', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:31:59,734 [INFO]   → r/galaxys5
2026-05-18 16:32:07,725 [INFO]      r/galaxys5: 0 posts in window
2026-05-18 16:32:07,726 [INFO]   → r/samsung
2026-05-18 16:32:16,772 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:32:16,773 [INFO]   → r/android
2026-05-18 16:32:25,212 [INFO]      r/android: 0 posts in window
2026-05-18 16:32:25,213 [INFO]   → r/technology
2026-05-18 16:32:33,222 [INFO]      r/technology: 0 posts in window
2026-05-18 16:32:33,224 [INFO]   → r/gadgets
2026-05-18 16:32:41,702 [INFO]      r/gadgets: 0 posts in window
2026-05-18 16:32:41,703 [INFO]   → r/smartphones
2026-05-18 16:32:50,208 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:32:50,209 [INFO]   TOTAL records uploaded for samsung_galaxy_s5: 0
2026-05-18 16:32:50,210 [WARNING]   ⚠ samsung_galaxy_s5 has 0 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:33:00,213 [INFO]
============================================================
2026-05-18 16:33:00,214 [INFO] Scraping: samsung_galaxy_s6
2026-05-18 16:33:00,215 [INFO] Window: 2015-01-10 → 2015-04-10
2026-05-18 16:33:00,216 [INFO] Subreddits: ['GalaxyS6', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:33:00,217 [INFO]   → r/GalaxyS6
2026-05-18 16:33:08,588 [INFO]      r/GalaxyS6: 0 posts in window
2026-05-18 16:33:08,589 [INFO]   → r/samsung
2026-05-18 16:33:17,687 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:33:17,688 [INFO]   → r/android
2026-05-18 16:33:26,001 [INFO]      r/android: 0 posts in window
2026-05-18 16:33:26,002 [INFO]   → r/technology
2026-05-18 16:33:33,888 [INFO]      r/technology: 0 posts in window
2026-05-18 16:33:33,889 [INFO]   → r/gadgets
2026-05-18 16:33:42,275 [INFO]      r/gadgets: 0 posts in window
2026-05-18 16:33:42,276 [INFO]   → r/smartphones
2026-05-18 16:33:50,926 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:33:50,927 [INFO]   TOTAL records uploaded for samsung_galaxy_s6: 0
2026-05-18 16:33:50,928 [WARNING]   ⚠ samsung_galaxy_s6 has 0 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:34:00,931 [INFO]
============================================================
2026-05-18 16:34:00,932 [INFO] Scraping: samsung_galaxy_s7_edge
2026-05-18 16:34:00,933 [INFO] Window: 2015-12-12 → 2016-03-11
2026-05-18 16:34:00,934 [INFO] Subreddits: ['GalaxyS7', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:34:00,935 [INFO]   → r/GalaxyS7
2026-05-18 16:34:11,292 [INFO]      r/GalaxyS7: 0 posts in window
2026-05-18 16:34:11,294 [INFO]   → r/samsung
2026-05-18 16:34:20,187 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:34:20,188 [INFO]   → r/android
2026-05-18 16:34:28,465 [INFO]      r/android: 0 posts in window
2026-05-18 16:34:28,469 [INFO]   → r/technology
2026-05-18 16:34:36,484 [INFO]      r/technology: 0 posts in window
2026-05-18 16:34:36,485 [INFO]   → r/gadgets
2026-05-18 16:34:44,634 [INFO]      r/gadgets: 0 posts in window
2026-05-18 16:34:44,635 [INFO]   → r/smartphones
2026-05-18 16:34:52,887 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:34:52,889 [INFO]   TOTAL records uploaded for samsung_galaxy_s7_edge: 0
2026-05-18 16:34:52,890 [WARNING]   ⚠ samsung_galaxy_s7_edge has 0 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:35:02,893 [INFO]
============================================================
2026-05-18 16:35:02,895 [INFO] Scraping: samsung_galaxy_s8
2026-05-18 16:35:02,896 [INFO] Window: 2017-01-21 → 2017-04-21
2026-05-18 16:35:02,897 [INFO] Subreddits: ['GalaxyS8', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:35:02,898 [INFO]   → r/GalaxyS8
2026-05-18 16:35:10,980 [INFO]      r/GalaxyS8: 0 posts in window
2026-05-18 16:35:10,981 [INFO]   → r/samsung
2026-05-18 16:35:19,594 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:35:19,596 [INFO]   → r/android
2026-05-18 16:35:27,505 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:36:28,116 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:37:28,657 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:38:29,277 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:39:29,816 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:40:31,206 [INFO]      r/android: 0 posts in window
2026-05-18 16:40:31,207 [INFO]   → r/technology
2026-05-18 16:40:39,675 [INFO]      r/technology: 0 posts in window
2026-05-18 16:40:39,676 [INFO]   → r/gadgets
2026-05-18 16:40:48,963 [INFO]      r/gadgets: 0 posts in window
2026-05-18 16:40:48,964 [INFO]   → r/smartphones
2026-05-18 16:40:57,528 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:40:57,529 [INFO]   TOTAL records uploaded for samsung_galaxy_s8: 0
2026-05-18 16:40:57,530 [WARNING]   ⚠ samsung_galaxy_s8 has 0 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:41:07,533 [INFO]
============================================================
2026-05-18 16:41:07,534 [INFO] Scraping: samsung_galaxy_s20_fe
2026-05-18 16:41:07,535 [INFO] Window: 2020-07-04 → 2020-10-02
2026-05-18 16:41:07,537 [INFO] Subreddits: ['GalaxyS20FE', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:41:07,538 [INFO]   → r/GalaxyS20FE
2026-05-18 16:41:16,572 [INFO]      r/GalaxyS20FE: 0 posts in window
2026-05-18 16:41:16,573 [INFO]   → r/samsung
2026-05-18 16:41:25,855 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:41:25,856 [INFO]   → r/android
2026-05-18 16:41:34,551 [INFO]      r/android: 0 posts in window
2026-05-18 16:41:34,552 [INFO]   → r/technology
2026-05-18 16:41:39,516 [INFO]      r/technology: 2 posts in window
2026-05-18 16:41:39,517 [INFO]   → r/gadgets
2026-05-18 16:42:10,770 [INFO]      r/gadgets: 23 posts in window
2026-05-18 16:42:10,771 [INFO]   → r/smartphones
2026-05-18 16:42:19,144 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:42:19,952 [INFO]   Uploaded 90 records → gs://thesis-bucket-vua/bronze/reddit/samsung_galaxy_s20_fe/1779115339.jsonl
2026-05-18 16:42:19,953 [INFO]   TOTAL records uploaded for samsung_galaxy_s20_fe: 90
2026-05-18 16:42:19,954 [WARNING]   ⚠ samsung_galaxy_s20_fe has 90 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:42:29,957 [INFO]
============================================================
2026-05-18 16:42:29,958 [INFO] Scraping: samsung_galaxy_s21_ultra
2026-05-18 16:42:29,959 [INFO] Window: 2020-10-31 → 2021-01-29
2026-05-18 16:42:29,961 [INFO] Subreddits: ['GalaxyS21', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:42:29,970 [INFO]   → r/GalaxyS21
2026-05-18 16:42:38,340 [INFO]      r/GalaxyS21: 0 posts in window
2026-05-18 16:42:38,341 [INFO]   → r/samsung
2026-05-18 16:42:47,531 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:42:47,532 [INFO]   → r/android
2026-05-18 16:42:55,918 [INFO]      r/android: 0 posts in window
2026-05-18 16:42:55,919 [INFO]   → r/technology
2026-05-18 16:43:20,027 [INFO]      r/technology: 24 posts in window
2026-05-18 16:43:20,028 [INFO]   → r/gadgets
2026-05-18 16:43:39,359 [INFO]      r/gadgets: 12 posts in window
2026-05-18 16:43:39,362 [INFO]   → r/smartphones
2026-05-18 16:43:47,906 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:43:48,020 [INFO]   Uploaded 151 records → gs://thesis-bucket-vua/bronze/reddit/samsung_galaxy_s21_ultra/1779115427.jsonl
2026-05-18 16:43:48,021 [INFO]   TOTAL records uploaded for samsung_galaxy_s21_ultra: 151
2026-05-18 16:43:48,022 [WARNING]   ⚠ samsung_galaxy_s21_ultra has 151 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:43:58,025 [INFO]
============================================================
2026-05-18 16:43:58,026 [INFO] Scraping: samsung_galaxy_s22_ultra
2026-05-18 16:43:58,027 [INFO] Window: 2021-11-27 → 2022-02-25
2026-05-18 16:43:58,028 [INFO] Subreddits: ['GalaxyS22', 'samsung', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:43:58,029 [INFO]   → r/GalaxyS22
2026-05-18 16:44:08,197 [INFO]      r/GalaxyS22: 0 posts in window
2026-05-18 16:44:08,199 [INFO]   → r/samsung
2026-05-18 16:44:17,894 [INFO]      r/samsung: 0 posts in window
2026-05-18 16:44:17,895 [INFO]   → r/android
2026-05-18 16:44:26,518 [INFO]      r/android: 0 posts in window
2026-05-18 16:44:26,520 [INFO]   → r/technology
2026-05-18 16:44:40,394 [INFO]      r/technology: 7 posts in window
2026-05-18 16:44:40,395 [INFO]   → r/gadgets
2026-05-18 16:44:46,804 [INFO]      r/gadgets: 2 posts in window
2026-05-18 16:44:46,805 [INFO]   → r/smartphones
2026-05-18 16:44:47,412 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:45:48,024 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:46:48,681 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:47:49,310 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:48:49,887 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:49:50,468 [WARNING] Rate limited — sleeping 60s
2026-05-18 16:50:58,967 [INFO]      r/smartphones: 0 posts in window
2026-05-18 16:50:59,539 [INFO]   Uploaded 87 records → gs://thesis-bucket-vua/bronze/reddit/samsung_galaxy_s22_ultra/1779115858.jsonl
2026-05-18 16:50:59,540 [INFO]   TOTAL records uploaded for samsung_galaxy_s22_ultra: 87
2026-05-18 16:50:59,541 [WARNING]   ⚠ samsung_galaxy_s22_ultra has 87 records — below minimum threshold of 500. Consider adding more subreddits or broadening the search query.
2026-05-18 16:51:09,544 [INFO]
============================================================
2026-05-18 16:51:09,545 [INFO] Scraping: google_pixel_3a
2026-05-18 16:51:09,546 [INFO] Window: 2019-02-06 → 2019-05-07
2026-05-18 16:51:09,547 [INFO] Subreddits: ['GooglePixel', 'pixel3a', 'android', 'technology', 'gadgets', 'smartphones']
2026-05-18 16:51:09,548 [INFO]   → r/GooglePixel
2026-05-18 16:51:18,598 [INFO]      r/GooglePixel: 0 posts in window
2026-05-18 16:51:18,600 [INFO]   → r/pixel3a
2026-05-18 16:51:27,039 [INFO]      r/pixel3a: 0 posts in window
2026-05-18 16:51:27,041 [INFO]   → r/android
2026-05-18 16:51:35,601 [INFO]      r/android: 0 posts in window
2026-05-18 16:51:35,602 [INFO]   → r/technology
2026-05-18 16:51:53,708 [INFO]      r/technology: 12 posts in window
2026-05-18 16:51:53,709 [INFO]   → r/gadgets
2026-05-18 16:52:10,234 [INFO]      r/gadgets: 6 posts in window
2026-05-18 16:52:10,235 [INFO]   → r/smartphones
2026-05-18 16:52:19,017 [INFO]      r/smartphones: 0 posts in window

==================================================
SCRAPING COMPLETE — Summary
==================================================

                       event  records  threshold_met
0          fire_hd_10_(2019)      227          False
1          fire_hd_8_(2020)_       63          False
2             fire_7_(2019)_        5          False
3             ipad_pro_2020_     2834           True
4          ipad_air_2_(2014)        5          False
5             macbook_air_m1     1307           True
6                ipad_mini_6      362          False
7            macbook_pro_16"     1026           True
8                 galaxy_s23      984           True
9                    pixel_5    21112           True
10                 iphone_14      257          False
11                 iphone_15      670           True
12                galaxy_s22      452          False
13                   pixel_7      751           True
14                 iphone_13     9561           True
15                galaxy_s21     4079           True
16                   pixel_6    40470           True
17            macbook_air_m2     3410           True
18               ipad_pro_m2     1598           True
19         samsung_galaxy_s4        0          False
20         samsung_galaxy_s5        0          False
21         samsung_galaxy_s6        0          False
22    samsung_galaxy_s7_edge        0          False
23         samsung_galaxy_s8        0          False
24     samsung_galaxy_s20_fe       90          False
25  samsung_galaxy_s21_ultra      151          False
26  samsung_galaxy_s22_ultra       87          False
27           google_pixel_3a      135          False
28         google_pixel_4_xl      196          False
29           google_pixel_4a       68          False
30            moto_g_3rd_gen        2          False
31           moto_g_4th_gen"        3          False
32               moto_g_fast      264          False
33         moto_g_power_2022      301          False
34                     lg_g3      179          False

Events meeting threshold (≥500): 12 / 35

In [38]:
# Testing 9b on 1 event
test_row = events[events["product_name"].str.contains("iPad Air 2", case=False)].iloc[0]
count = scrape_event_arctic_shift(test_row, fetch_comments=False)
print(f"Test result: {count} records")

2026-05-19 20:48:01,524 [INFO]
============================================================
2026-05-19 20:48:01,526 [INFO] Scraping (Arctic Shift): ipad_air_2_(2014)
2026-05-19 20:48:01,529 [INFO] Window: 2014-07-18 to 2014-10-16
2026-05-19 20:48:01,530 [INFO] Subreddits: ['ipad', 'apple', 'technology', 'gadgets']
2026-05-19 20:48:01,531 [INFO]   -> r/ipad
2026-05-19 20:48:02,570 [INFO]     status: 200
2026-05-19 20:48:02,571 [INFO]     posts returned: 0
2026-05-19 20:48:02,572 [INFO]      r/ipad: 0 posts
2026-05-19 20:48:02,573 [INFO]   -> r/apple
2026-05-19 20:48:03,209 [INFO]     status: 200
2026-05-19 20:48:03,211 [INFO]     posts returned: 2
2026-05-19 20:48:03,211 [INFO]      r/apple: 2 posts
2026-05-19 20:48:03,212 [INFO]   -> r/technology
2026-05-19 20:48:04,263 [INFO]     status: 200
2026-05-19 20:48:04,264 [INFO]     posts returned: 0
2026-05-19 20:48:04,265 [INFO]      r/technology: 0 posts
2026-05-19 20:48:04,266 [INFO]   -> r/gadgets
2026-05-19 20:48:04,967 [INFO]     status: 200
2026-05-19 20:48:04,968 [INFO]     posts returned: 0
2026-05-19 20:48:04,969 [INFO]      r/gadgets: 0 posts
2026-05-19 20:48:06,136 [INFO]   Uploaded 2 records → gs://thesis-bucket-vua/bronze/reddit/ipad_air_2_(2014)/1779216484.jsonl
2026-05-19 20:48:06,137 [INFO]   TOTAL: 2 records for ipad_air_2_(2014)
2026-05-19 20:48:06,139 [WARNING]   WARNING: 2 below threshold of 500

Test result: 2 records

In [33]:
#Cell 9b - connects to 6b
# Re-run failing old events using browse mode
browse_targets = [
    "iPhone 13", "Galaxy S21", "Pixel 6", "MacBook Air M2", "iPad Pro",
    "MacBook Air M1", "iPhone 14", "iPad mini 6", "iPad Pro 2020",
    "Fire HD 10", "Fire HD 8", "Fire 7", "iPad Air 2",
    "MacBook Pro 16", "Galaxy S23", "Pixel 5", "iPhone 15", "Galaxy S22", "Pixel 7",
    "Samsung Galaxy S4", "Samsung Galaxy S5", "Samsung Galaxy S6", "Samsung Galaxy S7 Edge",
    "Samsung Galaxy S8", "Samsung Galaxy S20 FE", "Samsung Galaxy S21 Ultra", "Samsung Galaxy S22 Ultra",
    "Google Pixel 3a", "Google Pixel 4 XL", "Google Pixel 4a", "Moto G 3rd Gen", "Moto G 4th Gen", "Moto G Fast", "Moto G Power 2022",
    "LG G3"
]

checkpoint = load_checkpoint()
results_browse = {}

for _, row in events.iterrows():
    if not any(t.lower() in row["product_name"].lower() for t in browse_targets):
        continue

    event_key = row["product_name"].lower().replace(" ", "_")

    # Only re-run if below threshold
    if checkpoint.get(event_key, {}).get("post_count", 0) >= MIN_POST_THRESHOLD:
        log.info(f"Skipping {event_key} — already at threshold")
        continue

    # Clear this event from checkpoint so it re-uploads cleanly
    if event_key in checkpoint:
        del checkpoint[event_key]
    save_checkpoint(checkpoint)

    try:
        count = scrape_event_arctic_shift(row, fetch_comments=True)
        results_browse[event_key] = count
        mark_complete(checkpoint, event_key, count)
    except Exception as e:
        log.error(f"Failed on {event_key}: {e}")
        results_browse[event_key] = -1

    time.sleep(SLEEP_BETWEEN_EVENTS)

# Summary
print("\n" + "="*50)
print("BROWSE MODE — Summary")
print("="*50)
summary = pd.DataFrame([
    {"event": k, "records": v, "threshold_met": v >= MIN_POST_THRESHOLD}
    for k, v in results_browse.items()
])
display(summary)

2026-05-18 17:21:26,698 [INFO]
============================================================
2026-05-18 17:21:26,700 [INFO] Scraping (Arctic Shift): fire_hd_10_(2019)
2026-05-18 17:21:26,701 [INFO] Window: 2019-08-01 to 2019-10-30
2026-05-18 17:21:26,702 [INFO] Subreddits: ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
2026-05-18 17:21:26,703 [INFO]   -> r/kindlefire

2026-05-18 17:21:28,469 [INFO]     status: 200
2026-05-18 17:21:28,470 [INFO]     posts returned: 1
2026-05-18 17:21:29,445 [INFO]      r/kindlefire: 1 posts
2026-05-18 17:21:29,447 [INFO]   -> r/amazonecho
2026-05-18 17:21:30,795 [INFO]     status: 200
2026-05-18 17:21:30,797 [INFO]     posts returned: 0
2026-05-18 17:21:30,798 [INFO]      r/amazonecho: 0 posts
2026-05-18 17:21:30,799 [INFO]   -> r/amazon
2026-05-18 17:21:32,760 [INFO]     status: 200
2026-05-18 17:21:32,761 [INFO]     posts returned: 0
2026-05-18 17:21:32,762 [INFO]      r/amazon: 0 posts
2026-05-18 17:21:32,763 [INFO]   -> r/tablets
2026-05-18 17:21:35,078 [INFO]     status: 200
2026-05-18 17:21:35,079 [INFO]     posts returned: 0
2026-05-18 17:21:35,080 [INFO]      r/tablets: 0 posts
2026-05-18 17:21:35,081 [INFO]   -> r/android
2026-05-18 17:21:36,853 [INFO]     status: 200
2026-05-18 17:21:36,854 [INFO]     posts returned: 0
2026-05-18 17:21:36,855 [INFO]      r/android: 0 posts
2026-05-18 17:21:36,856 [INFO]   -> r/gadgets
2026-05-18 17:21:37,666 [INFO]     status: 200
2026-05-18 17:21:37,667 [INFO]     posts returned: 0
2026-05-18 17:21:37,668 [INFO]      r/gadgets: 0 posts
2026-05-18 17:21:37,669 [INFO]   -> r/technology
2026-05-18 17:21:38,361 [INFO]     status: 200
2026-05-18 17:21:38,362 [INFO]     posts returned: 0
2026-05-18 17:21:38,363 [INFO]      r/technology: 0 posts
2026-05-18 17:21:39,466 [INFO]   Uploaded 13 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_10_(2019)/1779117698.jsonl
2026-05-18 17:21:39,467 [INFO]   TOTAL: 13 records for fire_hd_10_(2019)
2026-05-18 17:21:39,468 [WARNING]   WARNING: 13 below threshold of 500
2026-05-18 17:21:49,477 [INFO]
============================================================
2026-05-18 17:21:49,478 [INFO] Scraping (Arctic Shift): fire_hd_8_(2020)_
2026-05-18 17:21:49,479 [INFO] Window: 2020-07-02 to 2020-09-30
2026-05-18 17:21:49,480 [INFO] Subreddits: ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
2026-05-18 17:21:49,482 [INFO]   -> r/kindlefire
2026-05-18 17:21:50,703 [INFO]     status: 200
2026-05-18 17:21:50,705 [INFO]     posts returned: 7
2026-05-18 17:21:55,288 [INFO]      r/kindlefire: 7 posts
2026-05-18 17:21:55,289 [INFO]   -> r/amazonecho
2026-05-18 17:21:57,271 [INFO]     status: 200
2026-05-18 17:21:57,272 [INFO]     posts returned: 0
2026-05-18 17:21:57,273 [INFO]      r/amazonecho: 0 posts
2026-05-18 17:21:57,274 [INFO]   -> r/amazon
2026-05-18 17:21:59,202 [INFO]     status: 200
2026-05-18 17:21:59,203 [INFO]     posts returned: 1
2026-05-18 17:22:00,705 [INFO]      r/amazon: 1 posts
2026-05-18 17:22:00,706 [INFO]   -> r/tablets
2026-05-18 17:22:02,498 [INFO]     status: 200
2026-05-18 17:22:02,498 [INFO]     posts returned: 0
2026-05-18 17:22:02,499 [INFO]      r/tablets: 0 posts
2026-05-18 17:22:02,500 [INFO]   -> r/android
2026-05-18 17:22:04,243 [INFO]     status: 200
2026-05-18 17:22:04,245 [INFO]     posts returned: 3
2026-05-18 17:22:07,349 [INFO]      r/android: 3 posts
2026-05-18 17:22:07,350 [INFO]   -> r/gadgets
2026-05-18 17:22:07,855 [INFO]     status: 422
2026-05-18 17:22:07,857 [ERROR] HTTP 422: {"data":null,"error":"Timeout. Maybe slow down a bit"}
2026-05-18 17:22:07,858 [INFO]      r/gadgets: 0 posts
2026-05-18 17:22:07,859 [INFO]   -> r/technology
2026-05-18 17:22:08,420 [INFO]     status: 422
2026-05-18 17:22:08,421 [ERROR] HTTP 422: {"data":null,"error":"Timeout. Maybe slow down a bit"}
2026-05-18 17:22:08,422 [INFO]      r/technology: 0 posts
2026-05-18 17:22:08,548 [INFO]   Uploaded 108 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_8_(2020)_/1779117728.jsonl
2026-05-18 17:22:08,550 [INFO]   TOTAL: 108 records for fire_hd_8_(2020)_
2026-05-18 17:22:08,551 [WARNING]   WARNING: 108 below threshold of 500
2026-05-18 17:22:18,557 [INFO]
============================================================
2026-05-18 17:22:18,560 [INFO] Scraping (Arctic Shift): fire_7_(2019)_
2026-05-18 17:22:18,562 [INFO] Window: 2019-02-28 to 2019-05-29
2026-05-18 17:22:18,563 [INFO] Subreddits: ['kindlefire', 'tablets', 'android', 'gadgets']
2026-05-18 17:22:18,564 [INFO]   -> r/kindlefire
2026-05-18 17:22:20,009 [INFO]     status: 200
2026-05-18 17:22:20,009 [INFO]     posts returned: 1
2026-05-18 17:22:21,291 [INFO]      r/kindlefire: 1 posts
2026-05-18 17:22:21,293 [INFO]   -> r/tablets
2026-05-18 17:22:22,708 [INFO]     status: 200
2026-05-18 17:22:22,709 [INFO]     posts returned: 0
2026-05-18 17:22:22,711 [INFO]      r/tablets: 0 posts
2026-05-18 17:22:22,711 [INFO]   -> r/android
2026-05-18 17:22:23,881 [INFO]     status: 200
2026-05-18 17:22:23,882 [INFO]     posts returned: 0
2026-05-18 17:22:23,883 [INFO]      r/android: 0 posts
2026-05-18 17:22:23,884 [INFO]   -> r/gadgets
2026-05-18 17:22:24,767 [INFO]     status: 200
2026-05-18 17:22:24,768 [INFO]     posts returned: 0
2026-05-18 17:22:24,769 [INFO]      r/gadgets: 0 posts
2026-05-18 17:22:24,871 [INFO]   Uploaded 5 records → gs://thesis-bucket-vua/bronze/reddit/fire_7_(2019)_/1779117744.jsonl
2026-05-18 17:22:24,872 [INFO]   TOTAL: 5 records for fire_7_(2019)_
2026-05-18 17:22:24,873 [WARNING]   WARNING: 5 below threshold of 500
2026-05-18 17:22:34,881 [INFO] Skipping ipad_pro_2020_ — already at threshold
2026-05-18 17:22:34,884 [INFO]
============================================================
2026-05-18 17:22:34,885 [INFO] Scraping (Arctic Shift): ipad_air_2_(2014)
2026-05-18 17:22:34,886 [INFO] Window: 2014-07-18 to 2014-10-16
2026-05-18 17:22:34,887 [INFO] Subreddits: ['ipad', 'apple', 'technology', 'gadgets']
2026-05-18 17:22:34,888 [INFO]   -> r/ipad
2026-05-18 17:22:36,151 [INFO]     status: 200
2026-05-18 17:22:36,152 [INFO]     posts returned: 0
2026-05-18 17:22:36,153 [INFO]      r/ipad: 0 posts
2026-05-18 17:22:36,154 [INFO]   -> r/apple
2026-05-18 17:22:37,757 [INFO]     status: 200
2026-05-18 17:22:37,758 [INFO]     posts returned: 2
2026-05-18 17:22:39,547 [INFO]      r/apple: 2 posts
2026-05-18 17:22:39,548 [INFO]   -> r/technology
2026-05-18 17:22:41,336 [INFO]     status: 200
2026-05-18 17:22:41,337 [INFO]     posts returned: 0
2026-05-18 17:22:41,338 [INFO]      r/technology: 0 posts
2026-05-18 17:22:41,339 [INFO]   -> r/gadgets
2026-05-18 17:22:42,515 [INFO]     status: 200
2026-05-18 17:22:42,516 [INFO]     posts returned: 0
2026-05-18 17:22:42,518 [INFO]      r/gadgets: 0 posts
2026-05-18 17:22:42,612 [INFO]   Uploaded 5 records → gs://thesis-bucket-vua/bronze/reddit/ipad_air_2_(2014)/1779117762.jsonl
2026-05-18 17:22:42,614 [INFO]   TOTAL: 5 records for ipad_air_2_(2014)
2026-05-18 17:22:42,615 [WARNING]   WARNING: 5 below threshold of 500
2026-05-18 17:22:52,622 [INFO] Skipping macbook_air_m1 — already at threshold
2026-05-18 17:22:52,625 [INFO]
============================================================
2026-05-18 17:22:52,627 [INFO] Scraping (Arctic Shift): ipad_mini_6
2026-05-18 17:22:52,628 [INFO] Window: 2021-06-26 to 2021-09-24
2026-05-18 17:22:52,630 [INFO] Subreddits: ['ipad', 'apple', 'ios', 'tablets', 'gadgets', 'technology']
2026-05-18 17:22:52,633 [INFO]   -> r/ipad
2026-05-18 17:22:55,172 [INFO]     status: 200
2026-05-18 17:22:55,176 [INFO]     posts returned: 41
2026-05-18 17:23:31,528 [INFO]   Uploaded 203 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779117811.jsonl
2026-05-18 17:24:00,096 [INFO]   Uploaded 230 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779117839.jsonl
2026-05-18 17:24:10,235 [INFO]      r/ipad: 41 posts
2026-05-18 17:24:10,236 [INFO]   -> r/apple
2026-05-18 17:24:12,857 [INFO]     status: 200
2026-05-18 17:24:12,862 [INFO]     posts returned: 23
2026-05-18 17:24:23,184 [INFO]   Uploaded 206 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779117863.jsonl
2026-05-18 17:24:33,432 [INFO]   Uploaded 229 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779117873.jsonl
2026-05-18 17:24:37,208 [INFO]      r/apple: 23 posts
2026-05-18 17:24:37,209 [INFO]   -> r/ios
2026-05-18 17:24:38,382 [INFO]     status: 200
2026-05-18 17:24:38,383 [INFO]     posts returned: 1
2026-05-18 17:24:40,464 [INFO]      r/ios: 1 posts
2026-05-18 17:24:40,465 [INFO]   -> r/tablets
2026-05-18 17:24:42,720 [INFO]     status: 200
2026-05-18 17:24:42,721 [INFO]     posts returned: 1
2026-05-18 17:24:44,565 [INFO]      r/tablets: 1 posts
2026-05-18 17:24:44,566 [INFO]   -> r/gadgets
2026-05-18 17:24:45,539 [INFO]     status: 200
2026-05-18 17:24:45,540 [INFO]     posts returned: 0
2026-05-18 17:24:45,541 [INFO]      r/gadgets: 0 posts
2026-05-18 17:24:45,541 [INFO]   -> r/technology
2026-05-18 17:24:46,661 [INFO]     status: 200
2026-05-18 17:24:46,662 [INFO]     posts returned: 1
2026-05-18 17:24:47,798 [INFO]      r/technology: 1 posts
2026-05-18 17:24:47,904 [INFO]   Uploaded 139 records → gs://thesis-bucket-vua/bronze/reddit/ipad_mini_6/1779117887.jsonl
2026-05-18 17:24:47,905 [INFO]   TOTAL: 1007 records for ipad_mini_6
2026-05-18 17:24:57,911 [INFO] Skipping macbook_pro_16" — already at threshold
2026-05-18 17:24:57,912 [INFO] Skipping galaxy_s23 — already at threshold
2026-05-18 17:24:57,913 [INFO] Skipping pixel_5 — already at threshold
2026-05-18 17:24:57,916 [INFO]
============================================================
2026-05-18 17:24:57,917 [INFO] Scraping (Arctic Shift): iphone_14
2026-05-18 17:24:57,918 [INFO] Window: 2022-06-18 to 2022-09-16
2026-05-18 17:24:57,919 [INFO] Subreddits: ['iphone', 'apple', 'ios', 'AppleWatch', 'technology', 'gadgets', 'smartphones']
2026-05-18 17:24:57,921 [INFO]   -> r/iphone
2026-05-18 17:24:58,727 [INFO]     status: 200
2026-05-18 17:24:58,732 [INFO]     posts returned: 100
2026-05-18 17:25:30,087 [INFO]   Uploaded 203 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779117929.jsonl
2026-05-18 17:25:39,773 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779117939.jsonl
2026-05-18 17:26:07,682 [INFO]   Uploaded 200 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779117967.jsonl
2026-05-18 17:26:31,441 [INFO]   Uploaded 216 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779117991.jsonl
2026-05-18 17:26:38,595 [INFO]     status: 200
2026-05-18 17:26:38,602 [INFO]     posts returned: 100
2026-05-18 17:26:44,701 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118004.jsonl
2026-05-18 17:26:54,805 [INFO]   Uploaded 200 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118014.jsonl
2026-05-18 17:27:12,050 [INFO]   Uploaded 243 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118031.jsonl
2026-05-18 17:27:24,282 [INFO]   Uploaded 201 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118044.jsonl
2026-05-18 17:27:51,599 [INFO]   Uploaded 201 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118071.jsonl
2026-05-18 17:28:12,449 [INFO]   Uploaded 209 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118092.jsonl
2026-05-18 17:28:16,173 [INFO]     status: 200
2026-05-18 17:28:16,180 [INFO]     posts returned: 100
2026-05-18 17:28:28,913 [INFO]   Uploaded 221 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118108.jsonl
2026-05-18 17:28:57,634 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118137.jsonl
2026-05-18 17:29:17,035 [INFO]   Uploaded 283 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118156.jsonl
2026-05-18 17:29:29,614 [INFO]   Uploaded 225 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118169.jsonl
2026-05-18 17:29:51,859 [INFO]     status: 200
2026-05-18 17:29:51,865 [INFO]     posts returned: 100
2026-05-18 17:29:53,830 [INFO]   Uploaded 223 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118193.jsonl
2026-05-18 17:30:02,674 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118202.jsonl
2026-05-18 17:30:11,375 [INFO]   Uploaded 289 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118211.jsonl
2026-05-18 17:30:31,582 [INFO]   Uploaded 229 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118231.jsonl
2026-05-18 17:31:01,148 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118261.jsonl
2026-05-18 17:31:22,894 [INFO]     status: 200
2026-05-18 17:31:22,899 [INFO]     posts returned: 100
2026-05-18 17:31:26,057 [INFO]   Uploaded 243 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118285.jsonl
2026-05-18 17:31:36,805 [INFO]   Uploaded 226 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118296.jsonl
2026-05-18 17:31:48,935 [INFO]   Uploaded 238 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118308.jsonl
2026-05-18 17:32:14,606 [INFO]   Uploaded 203 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118334.jsonl
2026-05-18 17:32:40,402 [INFO]   Uploaded 204 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118360.jsonl
2026-05-18 17:32:51,687 [INFO]     status: 200
2026-05-18 17:32:51,692 [INFO]     posts returned: 100
2026-05-18 17:33:00,178 [INFO]   Uploaded 206 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118380.jsonl
2026-05-18 17:33:23,374 [INFO]   Uploaded 249 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118403.jsonl
2026-05-18 17:33:50,922 [INFO]   Uploaded 203 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118430.jsonl
2026-05-18 17:34:01,698 [INFO]   Uploaded 207 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118441.jsonl
2026-05-18 17:34:10,699 [INFO]   Uploaded 211 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118450.jsonl
2026-05-18 17:34:21,065 [INFO]     status: 200
2026-05-18 17:34:21,070 [INFO]     posts returned: 100
2026-05-18 17:34:22,859 [INFO]   Uploaded 206 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118462.jsonl
2026-05-18 17:34:44,301 [INFO]   Uploaded 217 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118484.jsonl
2026-05-18 17:35:13,658 [INFO]   Uploaded 226 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118513.jsonl
2026-05-18 17:35:46,875 [INFO]     status: 200
2026-05-18 17:35:46,881 [INFO]     posts returned: 100
2026-05-18 17:35:59,330 [INFO]   Uploaded 201 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118559.jsonl
2026-05-18 17:36:35,983 [INFO]   Uploaded 217 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118595.jsonl
2026-05-18 17:36:46,660 [INFO]   Uploaded 208 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118606.jsonl
2026-05-18 17:37:06,030 [INFO]   Uploaded 203 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118625.jsonl
2026-05-18 17:37:27,006 [INFO]     status: 200
2026-05-18 17:37:27,013 [INFO]     posts returned: 100
2026-05-18 17:37:32,396 [INFO]   Uploaded 225 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118652.jsonl
2026-05-18 17:37:37,140 [INFO]   Uploaded 244 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118657.jsonl
2026-05-18 17:37:42,119 [INFO]   Uploaded 200 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118662.jsonl
2026-05-18 17:37:58,066 [INFO]   Uploaded 210 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118677.jsonl
2026-05-18 17:38:05,864 [INFO]   Uploaded 239 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118685.jsonl
2026-05-18 17:38:12,630 [INFO]   Uploaded 249 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118692.jsonl
2026-05-18 17:38:24,750 [INFO]   Uploaded 277 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118704.jsonl
2026-05-18 17:38:30,511 [INFO]   Uploaded 260 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118710.jsonl
2026-05-18 17:38:45,359 [INFO]   Uploaded 288 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118725.jsonl
2026-05-18 17:38:51,793 [INFO]     status: 200
2026-05-18 17:38:51,799 [INFO]     posts returned: 100
2026-05-18 17:38:58,605 [INFO]   Uploaded 233 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118738.jsonl
2026-05-18 17:39:02,646 [INFO]   Uploaded 200 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118742.jsonl
2026-05-18 17:39:32,239 [INFO]   Uploaded 264 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118772.jsonl
2026-05-18 17:39:39,968 [INFO]   Uploaded 221 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118779.jsonl
2026-05-18 17:39:58,823 [INFO]   Uploaded 200 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118798.jsonl
2026-05-18 17:40:21,718 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118821.jsonl
2026-05-18 17:40:34,017 [INFO]   Uploaded 201 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118833.jsonl
2026-05-18 17:40:43,058 [INFO]     status: 200
2026-05-18 17:40:43,064 [INFO]     posts returned: 100
2026-05-18 17:40:49,683 [INFO]   Uploaded 231 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118849.jsonl
2026-05-18 17:40:58,726 [INFO]   Uploaded 229 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118858.jsonl
2026-05-18 17:41:20,308 [INFO]   Uploaded 238 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118880.jsonl
2026-05-18 17:41:34,029 [INFO]   Uploaded 202 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118893.jsonl
2026-05-18 17:41:47,522 [INFO]   Uploaded 217 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118907.jsonl
2026-05-18 17:42:01,645 [INFO]   Uploaded 211 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118921.jsonl
2026-05-18 17:42:26,093 [INFO]     status: 200
2026-05-18 17:42:26,099 [INFO]     posts returned: 100
2026-05-18 17:42:27,408 [INFO]   Uploaded 205 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118947.jsonl
2026-05-18 17:42:38,866 [INFO]   Uploaded 224 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118958.jsonl
2026-05-18 17:42:51,488 [INFO]   Uploaded 221 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118971.jsonl
2026-05-18 17:43:15,795 [INFO]   Uploaded 272 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779118995.jsonl
2026-05-18 17:43:26,173 [INFO]   Uploaded 207 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779119006.jsonl
2026-05-18 17:43:40,509 [INFO]   Uploaded 201 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779119020.jsonl
2026-05-18 17:43:48,454 [INFO]   Uploaded 263 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779119028.jsonl
2026-05-18 17:43:55,501 [INFO]     status: 422
2026-05-18 17:43:55,502 [ERROR] HTTP 422: {"data":null,"error":"Timeout. Maybe slow down a bit"}
2026-05-18 17:43:55,502 [INFO]      r/iphone: 1200 posts
2026-05-18 17:43:55,503 [INFO]   -> r/apple
2026-05-18 17:43:58,447 [INFO]     status: 200
2026-05-18 17:43:58,449 [INFO]     posts returned: 23
2026-05-18 17:44:08,646 [INFO]   Uploaded 200 records → gs://thesis-bucket-vua/bronze/reddit/iphone_14/1779119048.jsonl
2026-05-18 17:44:15,279 [INFO]      r/apple: 23 posts
2026-05-18 17:44:15,280 [INFO]   -> r/ios
2026-05-18 17:44:17,040 [INFO]     status: 200
2026-05-18 17:44:17,044 [INFO]     posts returned: 6
2026-05-18 17:44:23,060 [INFO]      r/ios: 6 posts
2026-05-18 17:44:23,061 [INFO]   -> r/AppleWatch
2026-05-18 17:44:24,308 [INFO]     status: 200
2026-05-18 17:44:24,309 [INFO]     posts returned: 1
2026-05-18 17:44:24,310 [INFO]      r/AppleWatch: 1 posts
2026-05-18 17:44:24,311 [INFO]   -> r/technology
2026-05-18 17:44:25,101 [INFO]     status: 200
2026-05-18 17:44:25,102 [INFO]     posts returned: 8
2026-05-18 17:44:28,303 [INFO]      r/technology: 8 posts
2026-05-18 17:44:28,304 [INFO]   -> r/gadgets
2026-05-18 17:44:30,228 [INFO]     status: 200
2026-05-18 17:44:30,230 [INFO]     posts returned: 2
2026-05-18 17:44:32,201 [INFO]      r/gadgets: 2 posts
2026-05-18 17:44:32,202 [INFO]   -> r/smartphones
2026-05-18 17:44:32,749 [INFO]     status: 422

==================================================
BROWSE MODE — Summary
==================================================

                       event  records  threshold_met
0          fire_hd_10_(2019)       13          False
1          fire_hd_8_(2020)_      108          False
2             fire_7_(2019)_        5          False
3          ipad_air_2_(2014)        5          False
4                ipad_mini_6     1007           True
5                  iphone_14    14848           True
6                 galaxy_s22     3610           True
7          samsung_galaxy_s4     2041           True
8          samsung_galaxy_s5      759           True
9          samsung_galaxy_s6     2328           True
10    samsung_galaxy_s7_edge     2229           True
11         samsung_galaxy_s8     5606           True
12     samsung_galaxy_s20_fe      632           True
13  samsung_galaxy_s21_ultra     2080           True
14  samsung_galaxy_s22_ultra     3007           True
15           google_pixel_3a     1354           True
16         google_pixel_4_xl     2717           True
17           google_pixel_4a     4156           True
18            moto_g_3rd_gen      482          False
19           moto_g_4th_gen"       59          False
20               moto_g_fast      210          False
21         moto_g_power_2022       26          False
22                     lg_g3     3293           True

In [ ]:
# Targeted re-scrape: Fire HD 10 and Fire HD 8 using Arctic Shift
fire_targets = {
    "Fire HD 10 (2019)": {
        "query_list": ["Fire HD 10"],
        "subreddits":  ["kindlefire", "amazonecho", "amazon", "tablets", "android", "gadgets", "technology"],
        "launch_date": "30/10/2019"
    },
    "Fire HD 8 (2020)": {
        "query_list": ["Fire HD 8"],
        "subreddits":  ["kindlefire", "amazonecho", "amazon", "tablets", "android", "gadgets", "technology"],
        "launch_date": "30/09/2020"
    }
}

results_fire = {}

for product_name, config in fire_targets.items():
    launch_dt    = pd.to_datetime(config["launch_date"], dayfirst=True, utc=True)
    window_start = launch_dt - timedelta(days=PRE_LAUNCH_DAYS)

    # Build a fake row matching what scrape_event_arctic_shift expects
    row = pd.Series({
        "product_name":    config["query"],   # clean query, no year bracket
        "launch_date":     launch_dt,
        "subreddits_list": config["subreddits"],
        "query_list":      config["query_list"],   # passes through to the function

    })

    # Clear checkpoint for this event
    event_key = product_name.lower().replace(" ", "_")
    checkpoint = load_checkpoint()
    if event_key in checkpoint:
        del checkpoint[event_key]
        save_checkpoint(checkpoint)
        log.info(f"Cleared checkpoint for {event_key}")

    log.info(f"Starting targeted scrape: {product_name}")
    log.info(f"Window: {window_start.date()} to {launch_dt.date()}")

    count = scrape_event_arctic_shift(row, fetch_comments=True)

    # Save under the original product key
    checkpoint = load_checkpoint()
    mark_complete(checkpoint, event_key, count)
    results_fire[product_name] = count

    time.sleep(SLEEP_BETWEEN_EVENTS)

print("\n" + "="*50)
print("Fire Tablets Scrape — Summary")
print("="*50)
for k, v in results_fire.items():
    status = "PASS" if v >= MIN_POST_THRESHOLD else "FAIL"
    print(f"  {k}: {v} records [{status}]")

2026-05-13 02:01:55,121 [INFO] Starting targeted scrape: Fire HD 10 (2019)
2026-05-13 02:01:55,124 [INFO] Window: 2019-08-01 to 2019-10-30
2026-05-13 02:01:55,125 [INFO]
============================================================
2026-05-13 02:01:55,127 [INFO] Scraping (Arctic Shift): fire_hd_10
2026-05-13 02:01:55,128 [INFO] Window: 2019-08-01 to 2019-10-30
2026-05-13 02:01:55,129 [INFO] Subreddits: ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
2026-05-13 02:01:55,130 [INFO]   -> r/kindlefire
2026-05-13 02:01:55,929 [INFO]     status: 200
2026-05-13 02:01:55,932 [INFO]     posts returned: 21
2026-05-13 02:02:09,677 [INFO]      r/kindlefire: 21 posts
2026-05-13 02:02:09,678 [INFO]   -> r/amazonecho
2026-05-13 02:02:10,261 [INFO]     status: 200
2026-05-13 02:02:10,262 [INFO]     posts returned: 0
2026-05-13 02:02:10,263 [INFO]      r/amazonecho: 0 posts
2026-05-13 02:02:10,264 [INFO]   -> r/amazon
2026-05-13 02:02:10,843 [INFO]     status: 200
2026-05-13 02:02:10,845 [INFO]     posts returned: 1
2026-05-13 02:02:11,838 [INFO]      r/amazon: 1 posts
2026-05-13 02:02:11,839 [INFO]   -> r/tablets
2026-05-13 02:02:12,612 [INFO]     status: 200
2026-05-13 02:02:12,613 [INFO]     posts returned: 1
2026-05-13 02:02:12,614 [INFO]      r/tablets: 1 posts
2026-05-13 02:02:12,615 [INFO]   -> r/android
2026-05-13 02:02:13,301 [INFO]     status: 200
2026-05-13 02:02:13,302 [INFO]     posts returned: 1
2026-05-13 02:02:14,576 [INFO]   Uploaded 224 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_10/1778630534.jsonl
2026-05-13 02:02:14,577 [INFO]      r/android: 1 posts
2026-05-13 02:02:14,578 [INFO]   -> r/gadgets
2026-05-13 02:02:15,148 [INFO]     status: 200
2026-05-13 02:02:15,149 [INFO]     posts returned: 1
2026-05-13 02:02:15,150 [INFO]      r/gadgets: 1 posts
2026-05-13 02:02:15,151 [INFO]   -> r/technology
2026-05-13 02:02:15,735 [INFO]     status: 200
2026-05-13 02:02:15,736 [INFO]     posts returned: 2
2026-05-13 02:02:15,737 [INFO]      r/technology: 2 posts
2026-05-13 02:02:15,824 [INFO]   Uploaded 3 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_10/1778630535.jsonl
2026-05-13 02:02:15,825 [INFO]   TOTAL: 227 records for fire_hd_10
2026-05-13 02:02:15,827 [WARNING]   WARNING: 227 below threshold of 500
2026-05-13 02:02:25,845 [INFO] Starting targeted scrape: Fire HD 8 (2020)
2026-05-13 02:02:25,846 [INFO] Window: 2020-07-02 to 2020-09-30
2026-05-13 02:02:25,848 [INFO]
============================================================
2026-05-13 02:02:25,849 [INFO] Scraping (Arctic Shift): fire_hd_8
2026-05-13 02:02:25,850 [INFO] Window: 2020-07-02 to 2020-09-30
2026-05-13 02:02:25,851 [INFO] Subreddits: ['kindlefire', 'amazonecho', 'amazon', 'tablets', 'android', 'gadgets', 'technology']
2026-05-13 02:02:25,852 [INFO]   -> r/kindlefire
2026-05-13 02:02:26,448 [INFO]     status: 200
2026-05-13 02:02:26,451 [INFO]     posts returned: 58
2026-05-13 02:02:53,082 [INFO]   Uploaded 224 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_8/1778630572.jsonl
2026-05-13 02:03:12,213 [INFO]      r/kindlefire: 58 posts
2026-05-13 02:03:12,214 [INFO]   -> r/amazonecho
2026-05-13 02:03:12,747 [INFO]     status: 200
2026-05-13 02:03:12,749 [INFO]     posts returned: 1
2026-05-13 02:03:12,750 [INFO]      r/amazonecho: 1 posts
2026-05-13 02:03:12,750 [INFO]   -> r/amazon
2026-05-13 02:03:13,289 [INFO]     status: 200
2026-05-13 02:03:13,290 [INFO]     posts returned: 3
2026-05-13 02:03:14,952 [INFO]      r/amazon: 3 posts
2026-05-13 02:03:14,953 [INFO]   -> r/tablets
2026-05-13 02:03:15,531 [INFO]     status: 200
2026-05-13 02:03:15,533 [INFO]     posts returned: 8
2026-05-13 02:03:20,731 [INFO]      r/tablets: 8 posts
2026-05-13 02:03:20,732 [INFO]   -> r/android
2026-05-13 02:03:21,382 [INFO]     status: 200
2026-05-13 02:03:21,383 [INFO]     posts returned: 4
2026-05-13 02:03:22,281 [INFO]   Uploaded 224 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_8/1778630602.jsonl
2026-05-13 02:03:24,107 [INFO]      r/android: 4 posts
2026-05-13 02:03:24,108 [INFO]   -> r/gadgets
2026-05-13 02:03:24,749 [INFO]     status: 200
2026-05-13 02:03:24,750 [INFO]     posts returned: 1
2026-05-13 02:03:25,576 [INFO]      r/gadgets: 1 posts
2026-05-13 02:03:25,577 [INFO]   -> r/technology
2026-05-13 02:03:26,108 [INFO]     status: 200
2026-05-13 02:03:26,109 [INFO]     posts returned: 0
2026-05-13 02:03:26,110 [INFO]      r/technology: 0 posts
2026-05-13 02:03:26,196 [INFO]   Uploaded 7 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_8/1778630606.jsonl
2026-05-13 02:03:26,197 [INFO]   TOTAL: 455 records for fire_hd_8
2026-05-13 02:03:26,198 [WARNING]   WARNING: 455 below threshold of 500

==================================================
Fire Tablets Scrape — Summary
==================================================
  Fire HD 10 (2019): 227 records [FAIL]
  Fire HD 8 (2020): 455 records [FAIL]

In [91]:
# Targeted re-scrape: Motorola and iPad
targets = {
    # ── Already in your list ─────────────────────────────────────
    "Acer Chromebook": {
        "query_list":       [ "Acer CB3", "Acer CB5"],
        "subreddits":  ["chromeos", "chromebook", "gadgets", "technology", "laptops", "tech"],
        "launch_date": "15/06/2015"
    },
    "iPad Pro 2018": {
        "query_list":       ["iPad Pro 11 inch", "iPad Pro 3rd generation"],
        "subreddits":  ["ipad", "apple", "technology", "tablets", "ios", "AppleLeaks"],
        "launch_date": "07/11/2018"
    },

    # ── Apple iPads ──────────────────────────────────────────────
    "iPad 7th Gen": {
        "query_list":       [ "iPad 2019", "iPad 10.2"],
        "subreddits":  ["ipad", "apple", "technology", "tablets", "ios"],
        "launch_date": "25/09/2019"
    },
    "iPad Pro M1": {
        "query_list":       [ "iPad Pro 2021", "iPad Pro 5th generation"],
        "subreddits":  ["ipad", "apple", "iPadPro", "technology", "tablets", "ios", "AppleLeaks"],
        "launch_date": "21/05/2021"
    },
    "iPad 9th Gen": {
        "query_list":       [ "iPad 2021", "iPad 10.2 2021"],
        "subreddits":  ["ipad", "apple", "technology", "tablets", "ios"],
        "launch_date": "24/09/2021"
    },
    "iPad Air M1": {
        "query_list":       [ "iPad Air 2022", "iPad Air 5th generation"],
        "subreddits":  ["ipad", "apple", "iPadPro", "technology", "tablets", "ios", "AppleLeaks"],
        "launch_date": "18/03/2022"
    },
    "iPad 10th Gen": {
        "query_list":       [ "iPad 2022", "iPad 10.9"],
        "subreddits":  ["ipad", "apple", "technology", "tablets", "ios", "AppleLeaks"],
        "launch_date": "26/10/2022"
    },

    # ── Amazon Fire tablets ──────────────────────────────────────
    "Fire HD 10 2021": {
        "query_list":       ["Fire HD 10 Plus"],
        "subreddits":  ["kindlefire", "amazon", "tablets", "android", "gadgets"],
        "launch_date": "26/10/2021"
    },

    # ── Google Pixel ─────────────────────────────────────────────
    "Pixel 3a": {
        "query_list":       ["Google Pixel 3a"],
        "subreddits":  ["GooglePixel", "pixel3a", "android", "technology", "gadgets"],
        "launch_date": "07/05/2019"
    },
    "Pixel 4 XL": {
        "query_list":       ["Google Pixel 4 XL"],
        "subreddits":  ["GooglePixel", "pixel4", "android", "technology", "gadgets"],
        "launch_date": "24/10/2019"
    },
    "Pixel 4a": {
        "query_list":       [ "Google Pixel 4a"],
        "subreddits":  ["GooglePixel", "pixel4a", "android", "technology", "gadgets"],
        "launch_date": "20/08/2020"
    },

    # ── Samsung Galaxy Tabs ──────────────────────────────────────
    "Galaxy Tab A 2016": {
        "query_list":       [ "Samsung Tab A 2016"],
        "subreddits":  ["GalaxyTab", "samsung", "android", "technology", "tablets"],
        "launch_date": "08/04/2016"
    },
    "Galaxy Tab A 2019": {
        "query_list":       [ "Samsung Tab A 10.1 2019"],
        "subreddits":  ["GalaxyTab", "samsung", "android", "technology", "tablets"],
        "launch_date": "26/04/2019"
    },
    "Galaxy Tab A8": {
        "query_list":       [ "Samsung Tab A8"],
        "subreddits":  ["GalaxyTab", "samsung", "android", "technology", "tablets"],
        "launch_date": "17/01/2022"
    },

    # ── Samsung Galaxy S ─────────────────────────────────────────
    "Galaxy S4": {
        "query_list":       ["Samsung Galaxy S4"],
        "subreddits":  ["galaxys4", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "27/04/2013"
    },
    "Galaxy S5": {
        "query_list":       [ "Samsung Galaxy S5"],
        "subreddits":  ["galaxys5", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "11/04/2014"
    },
    "Galaxy S6": {
        "query_list":       ["Samsung Galaxy S6"],
        "subreddits":  ["GalaxyS6", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "10/04/2015"
    },
    "Galaxy S7 Edge": {
        "query_list":       ["Samsung Galaxy S7 Edge"],
        "subreddits":  ["GalaxyS7", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "11/03/2016"
    },
    "Galaxy S8": {
        "query_list":       ["Samsung Galaxy S8"],
        "subreddits":  ["GalaxyS8", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "21/04/2017"
    },
    "Galaxy S20 FE": {
        "query_list":       ["Samsung Galaxy S20 FE"],
        "subreddits":  ["GalaxyS20FE", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "02/10/2020"
    },
    "Galaxy S21 Ultra": {
        "query_list":       ["Samsung Galaxy S21 Ultra"],
        "subreddits":  ["GalaxyS21", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "29/01/2021"
    },
    "Galaxy S22 Ultra": {
        "query_list":       [ "Samsung Galaxy S22 Ultra"],
        "subreddits":  ["GalaxyS22", "samsung", "android", "technology", "gadgets", "smartphones"],
        "launch_date": "25/02/2022"
    },

    # ── Asus / Microsoft ─────────────────────────────────────────
    "Asus Vivobook 15": {
        "query_list":       ["Asus VivoBook F512"],
        "subreddits":  ["ASUS", "laptops", "technology", "gadgets", "tech"],
        "launch_date": "01/09/2019"   # approximate — multiple variants
    },
    "Surface Pro 3": {
        "query_list":       ["Microsoft Surface Pro 3"],
        "subreddits":  ["Surface", "microsoft", "technology", "gadgets", "laptops", "tech"],
        "launch_date": "20/06/2014"
    },
}

results_fire = {}

for product_name, config in targets.items():
    launch_dt    = pd.to_datetime(config["launch_date"], dayfirst=True, utc=True)
    window_start = launch_dt - timedelta(days=PRE_LAUNCH_DAYS)

    # Build a fake row matching what scrape_event_arctic_shift expects
    row = pd.Series({
        "product_name":    event_key,   # clean query, no year bracket
        "launch_date":     launch_dt,
        "subreddits_list": config["subreddits"],
        "query_list":      config["query_list"],   # passes through to the function

    })

    # Clear checkpoint for this event
    event_key = product_name.lower().replace(" ", "_")
    checkpoint = load_checkpoint()
    if event_key in checkpoint:
        del checkpoint[event_key]
        save_checkpoint(checkpoint)
        log.info(f"Cleared checkpoint for {event_key}")

    log.info(f"Starting targeted scrape: {product_name}")
    log.info(f"Window: {window_start.date()} to {launch_dt.date()}")

    count = scrape_event_arctic_shift(row, fetch_comments=True)

    # Save under the original product key
    checkpoint = load_checkpoint()
    mark_complete(checkpoint, event_key, count)
    results_fire[product_name] = count

    time.sleep(SLEEP_BETWEEN_EVENTS)

print("\n" + "="*50)
print("Tablets Scrape — Summary")
print("="*50)
for k, v in results_fire.items():
    status = "PASS" if v >= MIN_POST_THRESHOLD else "FAIL"
    print(f"  {k}: {v} records [{status}]")

2026-05-23 18:41:56,655 [INFO] Starting targeted scrape: Acer Chromebook
2026-05-23 18:41:56,658 [INFO] Window: 2015-03-17 to 2015-06-15
2026-05-23 18:41:56,660 [INFO]
============================================================
2026-05-23 18:41:56,662 [INFO] Scraping (Arctic Shift): moto_g_4th_gen
2026-05-23 18:41:56,664 [INFO] Window: 2015-03-17 to 2015-06-15
2026-05-23 18:41:56,665 [INFO] Queries: ['Acer CB3', 'Acer CB5']
2026-05-23 18:41:56,690 [INFO] Subreddits: ['chromeos', 'chromebook', 'gadgets', 'technology', 'laptops', 'tech']
2026-05-23 18:41:56,692 [INFO]
  Query: 'Acer CB3'
2026-05-23 18:41:56,694 [INFO]   -> r/chromeos
2026-05-23 18:42:12,509 [INFO]      r/chromeos: 13 new posts
2026-05-23 18:42:14,511 [INFO]   -> r/chromebook
2026-05-23 18:42:15,134 [INFO]      r/chromebook: 0 new posts
2026-05-23 18:42:17,136 [INFO]   -> r/gadgets
2026-05-23 18:42:18,282 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:42:20,285 [INFO]   -> r/technology
2026-05-23 18:42:21,026 [INFO]      r/technology: 0 new posts
2026-05-23 18:42:23,028 [INFO]   -> r/laptops
2026-05-23 18:42:23,697 [INFO]      r/laptops: 0 new posts
2026-05-23 18:42:25,699 [INFO]   -> r/tech
2026-05-23 18:42:26,325 [INFO]      r/tech: 0 new posts
2026-05-23 18:42:28,958 [INFO]   Uploaded 76 records → gs://thesis-bucket-vua/bronze/reddit/moto_g_4th_gen/1779554548.jsonl
2026-05-23 18:42:28,959 [INFO]   Uploaded 76 records for query 'Acer CB3' -- total: 76
2026-05-23 18:42:33,961 [INFO]
  Query: 'Acer CB5'
2026-05-23 18:42:33,962 [INFO]   -> r/chromeos
2026-05-23 18:42:45,006 [INFO]      r/chromeos: 9 new posts
2026-05-23 18:42:47,008 [INFO]   -> r/chromebook
2026-05-23 18:42:47,629 [INFO]      r/chromebook: 0 new posts
2026-05-23 18:42:49,632 [INFO]   -> r/gadgets
2026-05-23 18:42:50,207 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:42:52,209 [INFO]   -> r/technology
2026-05-23 18:42:52,853 [INFO]      r/technology: 0 new posts
2026-05-23 18:42:54,855 [INFO]   -> r/laptops
2026-05-23 18:42:55,536 [INFO]      r/laptops: 0 new posts
2026-05-23 18:42:57,538 [INFO]   -> r/tech
2026-05-23 18:42:58,482 [INFO]      r/tech: 0 new posts
2026-05-23 18:43:00,578 [INFO]   Uploaded 44 records → gs://thesis-bucket-vua/bronze/reddit/moto_g_4th_gen/1779554580.jsonl
2026-05-23 18:43:00,579 [INFO]   Uploaded 44 records for query 'Acer CB5' -- total: 120
2026-05-23 18:43:05,582 [INFO]
  TOTAL: 120 records for moto_g_4th_gen
2026-05-23 18:43:05,583 [WARNING]   WARNING: 120 below threshold of 500
2026-05-23 18:43:15,606 [INFO] Starting targeted scrape: iPad Pro 2018
2026-05-23 18:43:15,607 [INFO] Window: 2018-08-09 to 2018-11-07
2026-05-23 18:43:15,609 [INFO]
============================================================
2026-05-23 18:43:15,610 [INFO] Scraping (Arctic Shift): acer_chromebook
2026-05-23 18:43:15,611 [INFO] Window: 2018-08-09 to 2018-11-07
2026-05-23 18:43:15,612 [INFO] Queries: ['iPad Pro 11 inch', 'iPad Pro 3rd generation']
2026-05-23 18:43:15,613 [INFO] Subreddits: ['ipad', 'apple', 'technology', 'tablets', 'ios', 'AppleLeaks']
2026-05-23 18:43:15,615 [INFO]
  Query: 'iPad Pro 11 inch'
2026-05-23 18:43:15,616 [INFO]   -> r/ipad
2026-05-23 18:43:32,419 [INFO]      r/ipad: 7 new posts
2026-05-23 18:43:34,421 [INFO]   -> r/apple
2026-05-23 18:43:43,569 [INFO]      r/apple: 7 new posts
2026-05-23 18:43:45,572 [INFO]   -> r/technology
2026-05-23 18:43:46,214 [INFO]      r/technology: 0 new posts
2026-05-23 18:43:48,216 [INFO]   -> r/tablets
2026-05-23 18:43:49,029 [INFO]      r/tablets: 0 new posts
2026-05-23 18:43:51,032 [INFO]   -> r/ios
2026-05-23 18:43:52,734 [INFO]      r/ios: 1 new posts
2026-05-23 18:43:54,736 [INFO]   -> r/AppleLeaks
2026-05-23 18:43:55,318 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 18:43:57,411 [INFO]   Uploaded 144 records → gs://thesis-bucket-vua/bronze/reddit/acer_chromebook/1779554637.jsonl
2026-05-23 18:43:57,412 [INFO]   Uploaded 144 records for query 'iPad Pro 11 inch' -- total: 144
2026-05-23 18:44:02,413 [INFO]
  Query: 'iPad Pro 3rd generation'
2026-05-23 18:44:02,414 [INFO]   -> r/ipad
2026-05-23 18:44:06,419 [INFO]      r/ipad: 1 new posts
2026-05-23 18:44:08,421 [INFO]   -> r/apple
2026-05-23 18:44:10,193 [INFO]      r/apple: 1 new posts
2026-05-23 18:44:12,195 [INFO]   -> r/technology
2026-05-23 18:44:13,001 [INFO]      r/technology: 0 new posts
2026-05-23 18:44:15,003 [INFO]   -> r/tablets
2026-05-23 18:44:15,645 [INFO]      r/tablets: 0 new posts
2026-05-23 18:44:17,648 [INFO]   -> r/ios
2026-05-23 18:44:18,607 [INFO]      r/ios: 0 new posts
2026-05-23 18:44:20,608 [INFO]   -> r/AppleLeaks
2026-05-23 18:44:21,430 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 18:44:23,509 [INFO]   Uploaded 6 records → gs://thesis-bucket-vua/bronze/reddit/acer_chromebook/1779554663.jsonl
2026-05-23 18:44:23,510 [INFO]   Uploaded 6 records for query 'iPad Pro 3rd generation' -- total: 150
2026-05-23 18:44:28,512 [INFO]
  TOTAL: 150 records for acer_chromebook
2026-05-23 18:44:28,513 [WARNING]   WARNING: 150 below threshold of 500
2026-05-23 18:44:38,536 [INFO] Starting targeted scrape: iPad 7th Gen
2026-05-23 18:44:38,537 [INFO] Window: 2019-06-27 to 2019-09-25
2026-05-23 18:44:38,539 [INFO]
============================================================
2026-05-23 18:44:38,541 [INFO] Scraping (Arctic Shift): ipad_pro_2018
2026-05-23 18:44:38,544 [INFO] Window: 2019-06-27 to 2019-09-25
2026-05-23 18:44:38,548 [INFO] Queries: ['iPad 2019', 'iPad 10.2']
2026-05-23 18:44:38,551 [INFO] Subreddits: ['ipad', 'apple', 'technology', 'tablets', 'ios']
2026-05-23 18:44:38,553 [INFO]
  Query: 'iPad 2019'
2026-05-23 18:44:38,554 [INFO]   -> r/ipad
2026-05-23 18:46:54,594 [INFO]      ... 100 posts so far in r/ipad
2026-05-23 18:47:17,949 [INFO]      r/ipad: 114 new posts
2026-05-23 18:47:19,950 [INFO]   -> r/apple
2026-05-23 18:47:25,138 [INFO]      r/apple: 25 new posts
2026-05-23 18:47:27,140 [INFO]   -> r/technology
2026-05-23 18:47:28,169 [INFO]      r/technology: 0 new posts
2026-05-23 18:47:30,170 [INFO]   -> r/tablets
2026-05-23 18:47:37,468 [INFO]      r/tablets: 6 new posts
2026-05-23 18:47:39,470 [INFO]   -> r/ios
2026-05-23 18:47:40,852 [INFO]      r/ios: 0 new posts
2026-05-23 18:47:43,831 [INFO]   Uploaded 1121 records → gs://thesis-bucket-vua/bronze/reddit/ipad_pro_2018/1779554862.jsonl
2026-05-23 18:47:43,832 [INFO]   Uploaded 1121 records for query 'iPad 2019' -- total: 1121
2026-05-23 18:47:48,834 [INFO]
  Query: 'iPad 10.2'
2026-05-23 18:47:48,839 [INFO]   -> r/ipad
2026-05-23 18:48:32,251 [INFO]      r/ipad: 28 new posts
2026-05-23 18:48:34,253 [INFO]   -> r/apple
2026-05-23 18:48:42,351 [INFO]      r/apple: 7 new posts
2026-05-23 18:48:44,353 [INFO]   -> r/technology
2026-05-23 18:48:45,411 [INFO]      r/technology: 0 new posts
2026-05-23 18:48:47,413 [INFO]   -> r/tablets
2026-05-23 18:48:48,001 [INFO]      r/tablets: 0 new posts
2026-05-23 18:48:50,004 [INFO]   -> r/ios
2026-05-23 18:48:53,247 [INFO]      r/ios: 2 new posts
2026-05-23 18:48:55,488 [INFO]   Uploaded 794 records → gs://thesis-bucket-vua/bronze/reddit/ipad_pro_2018/1779554935.jsonl
2026-05-23 18:48:55,490 [INFO]   Uploaded 794 records for query 'iPad 10.2' -- total: 1915
2026-05-23 18:49:00,491 [INFO]
  TOTAL: 1915 records for ipad_pro_2018
2026-05-23 18:49:10,514 [INFO] Starting targeted scrape: iPad Pro M1
2026-05-23 18:49:10,516 [INFO] Window: 2021-02-20 to 2021-05-21
2026-05-23 18:49:10,517 [INFO]
============================================================
2026-05-23 18:49:10,519 [INFO] Scraping (Arctic Shift): ipad_7th_gen
2026-05-23 18:49:10,520 [INFO] Window: 2021-02-20 to 2021-05-21
2026-05-23 18:49:10,521 [INFO] Queries: ['iPad Pro 2021', 'iPad Pro 5th generation']
2026-05-23 18:49:10,524 [INFO] Subreddits: ['ipad', 'apple', 'iPadPro', 'technology', 'tablets', 'ios', 'AppleLeaks']
2026-05-23 18:49:10,525 [INFO]
  Query: 'iPad Pro 2021'
2026-05-23 18:49:10,527 [INFO]   -> r/ipad
2026-05-23 18:51:29,672 [INFO]      ... 100 posts so far in r/ipad
2026-05-23 18:53:23,012 [INFO]      r/ipad: 193 new posts
2026-05-23 18:53:25,014 [INFO]   -> r/apple
2026-05-23 18:53:39,678 [INFO]      r/apple: 51 new posts
2026-05-23 18:53:41,681 [INFO]   -> r/iPadPro
2026-05-23 18:55:32,474 [INFO]      ... 100 posts so far in r/iPadPro
2026-05-23 18:56:48,948 [INFO]      r/iPadPro: 192 new posts
2026-05-23 18:56:50,951 [INFO]   -> r/technology
2026-05-23 18:56:57,013 [INFO]      r/technology: 9 new posts
2026-05-23 18:56:59,014 [INFO]   -> r/tablets
2026-05-23 18:56:59,907 [INFO]      r/tablets: 0 new posts
2026-05-23 18:57:01,909 [INFO]   -> r/ios
2026-05-23 18:57:03,689 [INFO]      r/ios: 1 new posts
2026-05-23 18:57:05,691 [INFO]   -> r/AppleLeaks
2026-05-23 18:57:06,239 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 18:57:09,113 [INFO]   Uploaded 3813 records → gs://thesis-bucket-vua/bronze/reddit/ipad_7th_gen/1779555428.jsonl
2026-05-23 18:57:09,115 [INFO]   Uploaded 3813 records for query 'iPad Pro 2021' -- total: 3813
2026-05-23 18:57:14,117 [INFO]
  Query: 'iPad Pro 5th generation'
2026-05-23 18:57:14,120 [INFO]   -> r/ipad
2026-05-23 18:57:23,842 [INFO]      r/ipad: 6 new posts
2026-05-23 18:57:25,844 [INFO]   -> r/apple
2026-05-23 18:57:26,904 [INFO]      r/apple: 1 new posts
2026-05-23 18:57:28,905 [INFO]   -> r/iPadPro
2026-05-23 18:57:33,933 [INFO]      r/iPadPro: 4 new posts
2026-05-23 18:57:35,935 [INFO]   -> r/technology
2026-05-23 18:57:36,576 [INFO]      r/technology: 0 new posts
2026-05-23 18:57:38,578 [INFO]   -> r/tablets
2026-05-23 18:57:39,122 [INFO]      r/tablets: 0 new posts
2026-05-23 18:57:41,125 [INFO]   -> r/ios
2026-05-23 18:57:41,667 [INFO]      r/ios: 0 new posts
2026-05-23 18:57:43,669 [INFO]   -> r/AppleLeaks
2026-05-23 18:57:44,386 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 18:57:46,627 [INFO]   Uploaded 57 records → gs://thesis-bucket-vua/bronze/reddit/ipad_7th_gen/1779555466.jsonl
2026-05-23 18:57:46,629 [INFO]   Uploaded 57 records for query 'iPad Pro 5th generation' -- total: 3870
2026-05-23 18:57:51,630 [INFO]
  TOTAL: 3870 records for ipad_7th_gen
2026-05-23 18:58:01,652 [INFO] Starting targeted scrape: iPad 9th Gen
2026-05-23 18:58:01,654 [INFO] Window: 2021-06-26 to 2021-09-24
2026-05-23 18:58:01,655 [INFO]
============================================================
2026-05-23 18:58:01,657 [INFO] Scraping (Arctic Shift): ipad_pro_m1
2026-05-23 18:58:01,658 [INFO] Window: 2021-06-26 to 2021-09-24
2026-05-23 18:58:01,659 [INFO] Queries: ['iPad 2021', 'iPad 10.2 2021']
2026-05-23 18:58:01,660 [INFO] Subreddits: ['ipad', 'apple', 'technology', 'tablets', 'ios']
2026-05-23 18:58:01,661 [INFO]
  Query: 'iPad 2021'
2026-05-23 18:58:01,662 [INFO]   -> r/ipad
2026-05-23 18:59:23,769 [INFO]      ... 100 posts so far in r/ipad
2026-05-23 19:00:05,682 [INFO]      r/ipad: 137 new posts
2026-05-23 19:00:07,685 [INFO]   -> r/apple
2026-05-23 19:00:38,535 [INFO]      r/apple: 40 new posts
2026-05-23 19:00:40,537 [INFO]   -> r/technology
2026-05-23 19:00:42,344 [INFO]      r/technology: 6 new posts
2026-05-23 19:00:44,346 [INFO]   -> r/tablets
2026-05-23 19:00:53,410 [INFO]      r/tablets: 7 new posts
2026-05-23 19:00:55,412 [INFO]   -> r/ios
2026-05-23 19:00:57,392 [INFO]      r/ios: 2 new posts
2026-05-23 19:00:59,536 [INFO]   Uploaded 996 records → gs://thesis-bucket-vua/bronze/reddit/ipad_pro_m1/1779555659.jsonl
2026-05-23 19:00:59,537 [INFO]   Uploaded 996 records for query 'iPad 2021' -- total: 996
2026-05-23 19:01:04,539 [INFO]
  Query: 'iPad 10.2 2021'
2026-05-23 19:01:04,541 [INFO]   -> r/ipad
2026-05-23 19:01:05,210 [INFO]      r/ipad: 0 new posts
2026-05-23 19:01:07,213 [INFO]   -> r/apple
2026-05-23 19:01:09,087 [INFO]      r/apple: 0 new posts
2026-05-23 19:01:11,090 [INFO]   -> r/technology
2026-05-23 19:01:13,439 [INFO]      r/technology: 0 new posts
2026-05-23 19:01:15,441 [INFO]   -> r/tablets
2026-05-23 19:01:16,862 [INFO]      r/tablets: 0 new posts
2026-05-23 19:01:18,864 [INFO]   -> r/ios
2026-05-23 19:01:19,788 [INFO]      r/ios: 0 new posts
2026-05-23 19:01:26,790 [INFO]
  TOTAL: 996 records for ipad_pro_m1
2026-05-23 19:01:36,813 [INFO] Starting targeted scrape: iPad Air M1
2026-05-23 19:01:36,814 [INFO] Window: 2021-12-18 to 2022-03-18
2026-05-23 19:01:36,815 [INFO]
============================================================
2026-05-23 19:01:36,817 [INFO] Scraping (Arctic Shift): ipad_9th_gen
2026-05-23 19:01:36,818 [INFO] Window: 2021-12-18 to 2022-03-18
2026-05-23 19:01:36,819 [INFO] Queries: ['iPad Air 2022', 'iPad Air 5th generation']
2026-05-23 19:01:36,820 [INFO] Subreddits: ['ipad', 'apple', 'iPadPro', 'technology', 'tablets', 'ios', 'AppleLeaks']
2026-05-23 19:01:36,821 [INFO]
  Query: 'iPad Air 2022'
2026-05-23 19:01:36,822 [INFO]   -> r/ipad
2026-05-23 19:01:45,097 [INFO]      r/ipad: 14 new posts
2026-05-23 19:01:47,099 [INFO]   -> r/apple
2026-05-23 19:01:53,114 [INFO]      r/apple: 9 new posts
2026-05-23 19:01:55,116 [INFO]   -> r/iPadPro
2026-05-23 19:01:58,482 [INFO]      r/iPadPro: 4 new posts
2026-05-23 19:02:00,484 [INFO]   -> r/technology
2026-05-23 19:02:01,058 [INFO]      r/technology: 0 new posts
2026-05-23 19:02:03,061 [INFO]   -> r/tablets
2026-05-23 19:02:03,898 [INFO]      r/tablets: 0 new posts
2026-05-23 19:02:05,900 [INFO]   -> r/ios
2026-05-23 19:02:06,589 [INFO]      r/ios: 0 new posts
2026-05-23 19:02:08,591 [INFO]   -> r/AppleLeaks
2026-05-23 19:02:09,161 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 19:02:11,273 [INFO]   Uploaded 251 records → gs://thesis-bucket-vua/bronze/reddit/ipad_9th_gen/1779555731.jsonl
2026-05-23 19:02:11,274 [INFO]   Uploaded 251 records for query 'iPad Air 2022' -- total: 251
2026-05-23 19:02:16,276 [INFO]
  Query: 'iPad Air 5th generation'
2026-05-23 19:02:16,277 [INFO]   -> r/ipad
2026-05-23 19:02:18,937 [INFO]      r/ipad: 1 new posts
2026-05-23 19:02:20,939 [INFO]   -> r/apple
2026-05-23 19:02:21,587 [INFO]      r/apple: 0 new posts
2026-05-23 19:02:23,588 [INFO]   -> r/iPadPro
2026-05-23 19:02:24,205 [INFO]      r/iPadPro: 2 new posts
2026-05-23 19:02:26,207 [INFO]   -> r/technology
2026-05-23 19:02:26,877 [INFO]      r/technology: 0 new posts
2026-05-23 19:02:28,880 [INFO]   -> r/tablets
2026-05-23 19:02:29,413 [INFO]      r/tablets: 0 new posts
2026-05-23 19:02:31,414 [INFO]   -> r/ios
2026-05-23 19:02:32,024 [INFO]      r/ios: 0 new posts
2026-05-23 19:02:34,026 [INFO]   -> r/AppleLeaks
2026-05-23 19:02:34,609 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 19:02:36,691 [INFO]   Uploaded 3 records → gs://thesis-bucket-vua/bronze/reddit/ipad_9th_gen/1779555756.jsonl
2026-05-23 19:02:36,692 [INFO]   Uploaded 3 records for query 'iPad Air 5th generation' -- total: 254
2026-05-23 19:02:41,694 [INFO]
  TOTAL: 254 records for ipad_9th_gen
2026-05-23 19:02:41,695 [WARNING]   WARNING: 254 below threshold of 500
2026-05-23 19:02:51,713 [INFO] Starting targeted scrape: iPad 10th Gen
2026-05-23 19:02:51,714 [INFO] Window: 2022-07-28 to 2022-10-26
2026-05-23 19:02:51,716 [INFO]
============================================================
2026-05-23 19:02:51,717 [INFO] Scraping (Arctic Shift): ipad_air_m1
2026-05-23 19:02:51,718 [INFO] Window: 2022-07-28 to 2022-10-26
2026-05-23 19:02:51,719 [INFO] Queries: ['iPad 2022', 'iPad 10.9']
2026-05-23 19:02:51,720 [INFO] Subreddits: ['ipad', 'apple', 'technology', 'tablets', 'ios', 'AppleLeaks']
2026-05-23 19:02:51,721 [INFO]
  Query: 'iPad 2022'
2026-05-23 19:02:51,722 [INFO]   -> r/ipad
2026-05-23 19:03:28,383 [INFO]      r/ipad: 79 new posts
2026-05-23 19:03:30,386 [INFO]   -> r/apple
2026-05-23 19:03:58,937 [INFO]      r/apple: 39 new posts
2026-05-23 19:04:00,939 [INFO]   -> r/technology
2026-05-23 19:04:01,604 [INFO]      r/technology: 1 new posts
2026-05-23 19:04:03,606 [INFO]   -> r/tablets
2026-05-23 19:04:09,562 [INFO]      r/tablets: 6 new posts
2026-05-23 19:04:11,564 [INFO]   -> r/ios
2026-05-23 19:04:13,228 [INFO]      r/ios: 1 new posts
2026-05-23 19:04:15,230 [INFO]   -> r/AppleLeaks
2026-05-23 19:04:15,857 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 19:04:17,987 [INFO]   Uploaded 715 records → gs://thesis-bucket-vua/bronze/reddit/ipad_air_m1/1779555857.jsonl
2026-05-23 19:04:17,988 [INFO]   Uploaded 715 records for query 'iPad 2022' -- total: 715
2026-05-23 19:04:22,991 [INFO]
  Query: 'iPad 10.9'
2026-05-23 19:04:22,992 [INFO]   -> r/ipad
2026-05-23 19:04:25,766 [INFO]      r/ipad: 13 new posts
2026-05-23 19:04:27,768 [INFO]   -> r/apple
2026-05-23 19:04:29,371 [INFO]      r/apple: 1 new posts
2026-05-23 19:04:31,373 [INFO]   -> r/technology
2026-05-23 19:04:31,949 [INFO]      r/technology: 0 new posts
2026-05-23 19:04:33,951 [INFO]   -> r/tablets
2026-05-23 19:04:34,616 [INFO]      r/tablets: 0 new posts
2026-05-23 19:04:36,619 [INFO]   -> r/ios
2026-05-23 19:04:37,140 [INFO]      r/ios: 0 new posts
2026-05-23 19:04:39,142 [INFO]   -> r/AppleLeaks
2026-05-23 19:04:39,791 [INFO]      r/AppleLeaks: 0 new posts
2026-05-23 19:04:41,889 [INFO]   Uploaded 106 records → gs://thesis-bucket-vua/bronze/reddit/ipad_air_m1/1779555881.jsonl
2026-05-23 19:04:41,890 [INFO]   Uploaded 106 records for query 'iPad 10.9' -- total: 821
2026-05-23 19:04:46,892 [INFO]
  TOTAL: 821 records for ipad_air_m1
2026-05-23 19:04:56,922 [INFO] Starting targeted scrape: Fire HD 10 2021
2026-05-23 19:04:56,924 [INFO] Window: 2021-07-28 to 2021-10-26
2026-05-23 19:04:56,926 [INFO]
============================================================
2026-05-23 19:04:56,927 [INFO] Scraping (Arctic Shift): ipad_10th_gen
2026-05-23 19:04:56,928 [INFO] Window: 2021-07-28 to 2021-10-26
2026-05-23 19:04:56,928 [INFO] Queries: ['Fire HD 10 Plus']
2026-05-23 19:04:56,930 [INFO] Subreddits: ['kindlefire', 'amazon', 'tablets', 'android', 'gadgets']
2026-05-23 19:04:56,930 [INFO]
  Query: 'Fire HD 10 Plus'
2026-05-23 19:04:56,933 [INFO]   -> r/kindlefire
2026-05-23 19:05:11,201 [INFO]      r/kindlefire: 11 new posts
2026-05-23 19:05:13,203 [INFO]   -> r/amazon
2026-05-23 19:05:15,829 [INFO]      r/amazon: 1 new posts
2026-05-23 19:05:17,832 [INFO]   -> r/tablets
2026-05-23 19:05:19,443 [INFO]      r/tablets: 2 new posts
2026-05-23 19:05:21,445 [INFO]   -> r/android
2026-05-23 19:05:22,039 [INFO]      r/android: 0 new posts
2026-05-23 19:05:24,041 [INFO]   -> r/gadgets
2026-05-23 19:05:24,633 [INFO]      r/gadgets: 0 new posts
2026-05-23 19:05:26,735 [INFO]   Uploaded 71 records → gs://thesis-bucket-vua/bronze/reddit/ipad_10th_gen/1779555926.jsonl
2026-05-23 19:05:26,737 [INFO]   Uploaded 71 records for query 'Fire HD 10 Plus' -- total: 71
2026-05-23 19:05:31,739 [INFO]
  TOTAL: 71 records for ipad_10th_gen
2026-05-23 19:05:31,740 [WARNING]   WARNING: 71 below threshold of 500
2026-05-23 19:05:41,760 [INFO] Starting targeted scrape: Pixel 3a
2026-05-23 19:05:41,762 [INFO] Window: 2019-02-06 to 2019-05-07
2026-05-23 19:05:41,763 [INFO]
============================================================
2026-05-23 19:05:41,764 [INFO] Scraping (Arctic Shift): fire_hd_10_2021
2026-05-23 19:05:41,765 [INFO] Window: 2019-02-06 to 2019-05-07
2026-05-23 19:05:41,767 [INFO] Queries: ['Google Pixel 3a']
2026-05-23 19:05:41,768 [INFO] Subreddits: ['GooglePixel', 'pixel3a', 'android', 'technology', 'gadgets']
2026-05-23 19:05:41,769 [INFO]
  Query: 'Google Pixel 3a'
2026-05-23 19:05:41,769 [INFO]   -> r/GooglePixel
2026-05-23 19:05:58,994 [INFO]      r/GooglePixel: 24 new posts
2026-05-23 19:06:00,996 [INFO]   -> r/pixel3a
2026-05-23 19:06:02,622 [INFO]      r/pixel3a: 1 new posts
2026-05-23 19:06:04,624 [INFO]   -> r/android
2026-05-23 19:06:28,236 [INFO]      r/android: 34 new posts
2026-05-23 19:06:30,238 [INFO]   -> r/technology
2026-05-23 19:06:30,821 [INFO]      r/technology: 4 new posts
2026-05-23 19:06:32,823 [INFO]   -> r/gadgets
2026-05-23 19:06:37,963 [INFO]      r/gadgets: 5 new posts
2026-05-23 19:06:40,167 [INFO]   Uploaded 1358 records → gs://thesis-bucket-vua/bronze/reddit/fire_hd_10_2021/1779555999.jsonl
2026-05-23 19:06:40,168 [INFO]   Uploaded 1358 records for query 'Google Pixel 3a' -- total: 1358
2026-05-23 19:06:45,170 [INFO]

==================================================
Tablets Scrape — Summary
==================================================
  Acer Chromebook: 120 records [FAIL]
  iPad Pro 2018: 150 records [FAIL]
  iPad 7th Gen: 1915 records [PASS]
  iPad Pro M1: 3870 records [PASS]
  iPad 9th Gen: 996 records [PASS]
  iPad Air M1: 254 records [FAIL]
  iPad 10th Gen: 821 records [PASS]
  Fire HD 10 2021: 71 records [FAIL]
  Pixel 3a: 1358 records [PASS]
  Pixel 4 XL: 2717 records [PASS]
  Pixel 4a: 5737 records [PASS]
  Galaxy Tab A 2016: 7 records [FAIL]
  Galaxy Tab A 2019: 0 records [FAIL]
  Galaxy Tab A8: 131 records [FAIL]
  Galaxy S4: 5065 records [PASS]
  Galaxy S5: 4925 records [PASS]
  Galaxy S6: 12394 records [PASS]
  Galaxy S7 Edge: 2942 records [PASS]
  Galaxy S8: 13846 records [PASS]
  Galaxy S20 FE: 632 records [PASS]
  Galaxy S21 Ultra: 2080 records [PASS]
  Galaxy S22 Ultra: 3007 records [PASS]
  Asus Vivobook 15: 2 records [FAIL]
  Surface Pro 3: 1217 records [PASS]

In [88]:
#Scrapping for Samsung tablets
targets = {
    "Galaxy Tab S2": {
        "query_list": [
            "Galaxy Tab S2",
            "Samsung Tab S2",
            "Tab S2 9.7",
            "Tab S2 8.0",
            "SM-T810",
            "SM-T710"
        ],
        "subreddits": [
            "GalaxyTab",
            "samsung",
            "Samsung",
            "SamsungGalaxy",
            "android",
            "technology",
            "tablets",
            "AndroidTablets",
            "pickanandroidforme",
            "hardware",
            "SamsungHelp",        # ← comma was missing before next entry
            "CheapAndroidTablets",
            "gadgets"
        ],
        "launch_date": "03/09/2015",
        "product_event": "galaxy_tab_s2",
        "posts_collected": 262,
        "posts_needed": 500
    },

    "Moto G Fast": {
        "query_list": [
            "Moto G Fast",
            "Motorola G Fast",
            "moto g fast 2020",
            "XT2045"
        ],
        "subreddits": [
            "motorola",
            "Motorola",
            "android",
            "AndroidQuestions",
            "pickanandroidforme",
            "budget_phones",
            "technology",
            "gadgets",
            "hardware",
            "nocontract"
        ],
        "launch_date": "18/06/2020",
        "product_event": "moto_g_fast",
        "posts_collected": 395,
        "posts_needed": 500
    },

    "Moto G 3rd Gen": {
        "query_list": [
            "Moto G 3rd gen",
            "Moto G 2015",
            "Motorola Moto G3",
            "XT1540",
            "XT1541",
            "XT1543",
            "Moto G3"
        ],
        "subreddits": [
            "motorola",
            "Motorola",
            "android",
            "AndroidQuestions",
            "pickanandroidforme",
            "budget_phones",
            "technology",
            "gadgets",
            "hardware",
            "nocontract"
        ],
        "launch_date": "28/07/2015",
        "product_event": "moto_g_3rd_gen",
        "posts_collected": 482,
        "posts_needed": 500
    },

    "Moto G 4th Gen": {
        "query_list": [
            "Moto G4",
            "Moto G 4th gen",
            "Moto G 2016",
            "Motorola Moto G4",
            "Moto G4 Plus",
            "Moto G4 Play",
            "XT1622",
            "XT1626",
            "XT1625"
        ],
        "subreddits": [
            "motorola",
            "Motorola",
            "android",
            "AndroidQuestions",
            "pickanandroidforme",
            "budget_phones",
            "technology",
            "gadgets",
            "hardware",
            "nocontract",
            "MotoG"
        ],
        "launch_date": "17/05/2016",
        "product_event": "moto_g_4th_gen",
        "posts_collected": 64,
        "posts_needed": 500
    }
}

results = {}

for product_name, config in targets.items():
    launch_dt    = pd.to_datetime(config["launch_date"], dayfirst=True, utc=True)
    window_start = launch_dt - timedelta(days=PRE_LAUNCH_DAYS)

    # Build a fake row matching what scrape_event_arctic_shift expects
    row = pd.Series({
        "product_name":    event_key,   # clean query, no year bracket
        "launch_date":     launch_dt,
        "subreddits_list": config["subreddits"],
        "query_list":      config["query_list"],   # passes through to the function
    })

    # Clear checkpoint for this event
    event_key = product_name.lower().replace(" ", "_")
    checkpoint = load_checkpoint()
    if event_key in checkpoint:
        del checkpoint[event_key]
        save_checkpoint(checkpoint)
        log.info(f"Cleared checkpoint for {event_key}")

    log.info(f"Starting targeted scrape: {product_name}")
    log.info(f"Window: {window_start.date()} to {launch_dt.date()}")

    count = scrape_event_arctic_shift(row, fetch_comments=True)

    # Save under the original product key
    checkpoint = load_checkpoint()
    mark_complete(checkpoint, event_key, count)
    results[product_name] = count

    time.sleep(SLEEP_BETWEEN_EVENTS)

print("\n" + "="*50)
print("Tablets Scrape — Summary")
print("="*50)
for k, v in results.items():
    status = "PASS" if v >= MIN_POST_THRESHOLD else "FAIL"
    print(f"  {k}: {v} records [{status}]")

2026-05-23 18:11:36,962 [INFO] Starting targeted scrape: Galaxy Tab S2
2026-05-23 18:11:36,963 [INFO] Window: 2015-06-05 to 2015-09-03
2026-05-23 18:11:36,964 [INFO]
============================================================
2026-05-23 18:11:36,965 [INFO] Scraping (Arctic Shift): galaxy_tab_s2
2026-05-23 18:11:36,966 [INFO] Window: 2015-06-05 to 2015-09-03
2026-05-23 18:11:36,967 [INFO] Queries: ['Galaxy Tab S2', 'Samsung Tab S2', 'Tab S2 9.7', 'Tab S2 8.0', 'SM-T810', 'SM-T710']
2026-05-23 18:11:36,968 [INFO] Subreddits: ['GalaxyTab', 'samsung', 'Samsung', 'SamsungGalaxy', 'android', 'technology', 'tablets', 'AndroidTablets', 'pickanandroidforme', 'hardware', 'SamsungHelp', 'CheapAndroidTablets', 'gadgets']
2026-05-23 18:11:36,969 [INFO]
  Query: 'Galaxy Tab S2'
2026-05-23 18:11:36,969 [INFO]   -> r/GalaxyTab

2026-05-23 18:11:37,840 [INFO]      r/GalaxyTab: 8 new posts
2026-05-23 18:11:39,843 [INFO]   -> r/samsung
2026-05-23 18:11:45,431 [INFO]      r/samsung: 12 new posts
2026-05-23 18:11:47,431 [INFO]   -> r/Samsung
2026-05-23 18:11:48,019 [INFO]      r/Samsung: 0 new posts
2026-05-23 18:11:50,022 [INFO]   -> r/SamsungGalaxy
2026-05-23 18:11:51,698 [INFO]      r/SamsungGalaxy: 2 new posts
2026-05-23 18:11:53,700 [INFO]   -> r/android
2026-05-23 18:12:12,413 [INFO]      r/android: 27 new posts
2026-05-23 18:12:14,415 [INFO]   -> r/technology
2026-05-23 18:12:26,995 [INFO]      r/technology: 29 new posts
2026-05-23 18:12:28,996 [INFO]   -> r/tablets
2026-05-23 18:12:30,677 [INFO]      r/tablets: 3 new posts
2026-05-23 18:12:32,679 [INFO]   -> r/AndroidTablets
2026-05-23 18:12:34,261 [INFO]      r/AndroidTablets: 2 new posts
2026-05-23 18:12:36,263 [INFO]   -> r/pickanandroidforme
2026-05-23 18:12:36,855 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:12:38,857 [INFO]   -> r/hardware
2026-05-23 18:12:39,418 [INFO]      r/hardware: 0 new posts
2026-05-23 18:12:41,420 [INFO]   -> r/SamsungHelp
2026-05-23 18:12:42,129 [INFO]      r/SamsungHelp: 0 new posts
2026-05-23 18:12:44,131 [INFO]   -> r/CheapAndroidTablets
2026-05-23 18:12:44,951 [INFO]      r/CheapAndroidTablets: 0 new posts
2026-05-23 18:12:46,953 [INFO]   -> r/gadgets
2026-05-23 18:12:57,938 [INFO]      r/gadgets: 16 new posts
2026-05-23 18:13:00,644 [INFO]   Uploaded 508 records → gs://thesis-bucket-vua/bronze/reddit/galaxy_tab_s2/1779552779.jsonl
2026-05-23 18:13:00,645 [INFO]   Uploaded 508 records for query 'Galaxy Tab S2' -- total: 508
2026-05-23 18:13:05,647 [INFO]
  Query: 'Samsung Tab S2'
2026-05-23 18:13:05,648 [INFO]   -> r/GalaxyTab
2026-05-23 18:13:06,419 [INFO]      r/GalaxyTab: 0 new posts
2026-05-23 18:13:08,421 [INFO]   -> r/samsung
2026-05-23 18:13:09,046 [INFO]      r/samsung: 0 new posts
2026-05-23 18:13:11,049 [INFO]   -> r/Samsung
2026-05-23 18:13:11,989 [INFO]      r/Samsung: 0 new posts
2026-05-23 18:13:13,990 [INFO]   -> r/SamsungGalaxy
2026-05-23 18:13:14,567 [INFO]      r/SamsungGalaxy: 0 new posts
2026-05-23 18:13:16,569 [INFO]   -> r/android
2026-05-23 18:13:18,172 [INFO]      r/android: 1 new posts
2026-05-23 18:13:20,173 [INFO]   -> r/technology
2026-05-23 18:13:21,430 [INFO]      r/technology: 4 new posts
2026-05-23 18:13:23,432 [INFO]   -> r/tablets
2026-05-23 18:13:24,144 [INFO]      r/tablets: 0 new posts
2026-05-23 18:13:26,147 [INFO]   -> r/AndroidTablets
2026-05-23 18:13:26,818 [INFO]      r/AndroidTablets: 0 new posts
2026-05-23 18:13:28,820 [INFO]   -> r/pickanandroidforme
2026-05-23 18:13:29,395 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:13:31,398 [INFO]   -> r/hardware
2026-05-23 18:13:31,961 [INFO]      r/hardware: 0 new posts
2026-05-23 18:13:33,963 [INFO]   -> r/SamsungHelp
2026-05-23 18:13:34,505 [INFO]      r/SamsungHelp: 0 new posts
2026-05-23 18:13:36,507 [INFO]   -> r/CheapAndroidTablets
2026-05-23 18:13:37,077 [INFO]      r/CheapAndroidTablets: 0 new posts
2026-05-23 18:13:39,079 [INFO]   -> r/gadgets
2026-05-23 18:13:39,716 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:13:41,818 [INFO]   Uploaded 9 records → gs://thesis-bucket-vua/bronze/reddit/galaxy_tab_s2/1779552821.jsonl
2026-05-23 18:13:41,820 [INFO]   Uploaded 9 records for query 'Samsung Tab S2' -- total: 517
2026-05-23 18:13:46,821 [INFO]
  Query: 'Tab S2 9.7'
2026-05-23 18:13:46,822 [INFO]   -> r/GalaxyTab
2026-05-23 18:13:47,409 [INFO]      r/GalaxyTab: 0 new posts
2026-05-23 18:13:49,411 [INFO]   -> r/samsung
2026-05-23 18:13:50,094 [INFO]      r/samsung: 0 new posts
2026-05-23 18:13:52,096 [INFO]   -> r/Samsung
2026-05-23 18:13:52,862 [INFO]      r/Samsung: 0 new posts
2026-05-23 18:13:54,863 [INFO]   -> r/SamsungGalaxy
2026-05-23 18:13:55,478 [INFO]      r/SamsungGalaxy: 0 new posts
2026-05-23 18:13:57,481 [INFO]   -> r/android
2026-05-23 18:13:58,470 [INFO]      r/android: 0 new posts
2026-05-23 18:14:00,472 [INFO]   -> r/technology
2026-05-23 18:14:01,807 [INFO]      r/technology: 0 new posts
2026-05-23 18:14:03,810 [INFO]   -> r/tablets
2026-05-23 18:14:04,774 [INFO]      r/tablets: 0 new posts
2026-05-23 18:14:06,776 [INFO]   -> r/AndroidTablets
2026-05-23 18:14:07,459 [INFO]      r/AndroidTablets: 0 new posts
2026-05-23 18:14:09,461 [INFO]   -> r/pickanandroidforme
2026-05-23 18:14:10,230 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:14:12,233 [INFO]   -> r/hardware
2026-05-23 18:14:13,021 [INFO]      r/hardware: 0 new posts
2026-05-23 18:14:15,023 [INFO]   -> r/SamsungHelp
2026-05-23 18:14:15,814 [INFO]      r/SamsungHelp: 0 new posts
2026-05-23 18:14:17,817 [INFO]   -> r/CheapAndroidTablets
2026-05-23 18:14:18,427 [INFO]      r/CheapAndroidTablets: 0 new posts
2026-05-23 18:14:20,430 [INFO]   -> r/gadgets
2026-05-23 18:14:21,151 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:14:28,154 [INFO]
  Query: 'Tab S2 8.0'
2026-05-23 18:14:28,155 [INFO]   -> r/GalaxyTab
2026-05-23 18:14:28,754 [INFO]      r/GalaxyTab: 0 new posts
2026-05-23 18:14:30,757 [INFO]   -> r/samsung
2026-05-23 18:14:31,355 [INFO]      r/samsung: 0 new posts
2026-05-23 18:14:33,357 [INFO]   -> r/Samsung
2026-05-23 18:14:33,950 [INFO]      r/Samsung: 0 new posts
2026-05-23 18:14:35,952 [INFO]   -> r/SamsungGalaxy
2026-05-23 18:14:36,672 [INFO]      r/SamsungGalaxy: 0 new posts
2026-05-23 18:14:38,674 [INFO]   -> r/android
2026-05-23 18:14:39,294 [INFO]      r/android: 0 new posts
2026-05-23 18:14:41,296 [INFO]   -> r/technology
2026-05-23 18:14:41,998 [INFO]      r/technology: 0 new posts
2026-05-23 18:14:44,001 [INFO]   -> r/tablets
2026-05-23 18:14:44,578 [INFO]      r/tablets: 0 new posts
2026-05-23 18:14:46,580 [INFO]   -> r/AndroidTablets
2026-05-23 18:14:47,166 [INFO]      r/AndroidTablets: 0 new posts
2026-05-23 18:14:49,168 [INFO]   -> r/pickanandroidforme
2026-05-23 18:14:49,734 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:14:51,737 [INFO]   -> r/hardware
2026-05-23 18:14:52,367 [INFO]      r/hardware: 0 new posts
2026-05-23 18:14:54,370 [INFO]   -> r/SamsungHelp
2026-05-23 18:14:54,947 [INFO]      r/SamsungHelp: 0 new posts
2026-05-23 18:14:56,949 [INFO]   -> r/CheapAndroidTablets
2026-05-23 18:14:57,568 [INFO]      r/CheapAndroidTablets: 0 new posts
2026-05-23 18:14:59,570 [INFO]   -> r/gadgets
2026-05-23 18:15:01,370 [WARNING] Rate limited (422) -- sleeping 60s
2026-05-23 18:16:02,139 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:16:09,141 [INFO]
  Query: 'SM-T810'
2026-05-23 18:16:09,142 [INFO]   -> r/GalaxyTab
2026-05-23 18:16:10,533 [INFO]      r/GalaxyTab: 0 new posts
2026-05-23 18:16:12,535 [INFO]   -> r/samsung
2026-05-23 18:16:15,893 [INFO]      r/samsung: 0 new posts
2026-05-23 18:16:17,896 [INFO]   -> r/Samsung
2026-05-23 18:16:19,074 [INFO]      r/Samsung: 0 new posts
2026-05-23 18:16:21,076 [INFO]   -> r/SamsungGalaxy
2026-05-23 18:16:21,631 [INFO]      r/SamsungGalaxy: 0 new posts
2026-05-23 18:16:23,633 [INFO]   -> r/android
2026-05-23 18:16:24,479 [INFO]      r/android: 0 new posts
2026-05-23 18:16:26,480 [INFO]   -> r/technology
2026-05-23 18:16:27,118 [INFO]      r/technology: 0 new posts
2026-05-23 18:16:29,121 [INFO]   -> r/tablets
2026-05-23 18:16:30,241 [INFO]      r/tablets: 0 new posts
2026-05-23 18:16:32,243 [INFO]   -> r/AndroidTablets
2026-05-23 18:16:33,153 [INFO]      r/AndroidTablets: 0 new posts
2026-05-23 18:16:35,156 [INFO]   -> r/pickanandroidforme
2026-05-23 18:16:35,976 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:16:37,978 [INFO]   -> r/hardware
2026-05-23 18:16:39,432 [INFO]      r/hardware: 0 new posts
2026-05-23 18:16:41,434 [INFO]   -> r/SamsungHelp
2026-05-23 18:16:42,359 [INFO]      r/SamsungHelp: 0 new posts
2026-05-23 18:16:44,361 [INFO]   -> r/CheapAndroidTablets
2026-05-23 18:16:44,957 [INFO]      r/CheapAndroidTablets: 0 new posts
2026-05-23 18:16:46,959 [INFO]   -> r/gadgets
2026-05-23 18:16:47,781 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:16:54,784 [INFO]
  Query: 'SM-T710'
2026-05-23 18:16:54,785 [INFO]   -> r/GalaxyTab
2026-05-23 18:16:55,381 [INFO]      r/GalaxyTab: 0 new posts
2026-05-23 18:16:57,382 [INFO]   -> r/samsung
2026-05-23 18:16:58,080 [INFO]      r/samsung: 0 new posts
2026-05-23 18:17:00,083 [INFO]   -> r/Samsung
2026-05-23 18:17:00,811 [INFO]      r/Samsung: 0 new posts
2026-05-23 18:17:02,813 [INFO]   -> r/SamsungGalaxy
2026-05-23 18:17:03,862 [INFO]      r/SamsungGalaxy: 0 new posts
2026-05-23 18:17:05,863 [INFO]   -> r/android
2026-05-23 18:17:06,593 [INFO]      r/android: 0 new posts
2026-05-23 18:17:08,596 [INFO]   -> r/technology
2026-05-23 18:17:09,211 [INFO]      r/technology: 0 new posts
2026-05-23 18:17:11,212 [INFO]   -> r/tablets
2026-05-23 18:17:11,930 [INFO]      r/tablets: 0 new posts
2026-05-23 18:17:13,932 [INFO]   -> r/AndroidTablets
2026-05-23 18:17:14,677 [INFO]      r/AndroidTablets: 0 new posts
2026-05-23 18:17:16,680 [INFO]   -> r/pickanandroidforme
2026-05-23 18:17:17,283 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:17:19,285 [INFO]   -> r/hardware
2026-05-23 18:17:20,132 [INFO]      r/hardware: 0 new posts
2026-05-23 18:17:22,133 [INFO]   -> r/SamsungHelp
2026-05-23 18:17:22,885 [INFO]      r/SamsungHelp: 0 new posts
2026-05-23 18:17:24,887 [INFO]   -> r/CheapAndroidTablets
2026-05-23 18:17:25,673 [INFO]      r/CheapAndroidTablets: 0 new posts
2026-05-23 18:17:27,675 [INFO]   -> r/gadgets
2026-05-23 18:17:28,597 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:17:35,600 [INFO]
  TOTAL: 517 records for galaxy_tab_s2
2026-05-23 18:17:45,622 [INFO] Cleared checkpoint for moto_g_fast
2026-05-23 18:17:45,623 [INFO] Starting targeted scrape: Moto G Fast
2026-05-23 18:17:45,624 [INFO] Window: 2020-03-20 to 2020-06-18
2026-05-23 18:17:45,626 [INFO]
============================================================
2026-05-23 18:17:45,627 [INFO] Scraping (Arctic Shift): galaxy_tab_s2
2026-05-23 18:17:45,628 [INFO] Window: 2020-03-20 to 2020-06-18
2026-05-23 18:17:45,629 [INFO] Queries: ['Moto G Fast', 'Motorola G Fast', 'moto g fast 2020', 'XT2045']
2026-05-23 18:17:45,630 [INFO] Subreddits: ['motorola', 'Motorola', 'android', 'AndroidQuestions', 'pickanandroidforme', 'budget_phones', 'technology', 'gadgets', 'hardware', 'nocontract']
2026-05-23 18:17:45,631 [INFO]
  Query: 'Moto G Fast'
2026-05-23 18:17:45,632 [INFO]   -> r/motorola
2026-05-23 18:17:46,180 [INFO]      r/motorola: 1 new posts
2026-05-23 18:17:48,182 [INFO]   -> r/Motorola
2026-05-23 18:17:48,724 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:17:50,726 [INFO]   -> r/android
2026-05-23 18:17:54,829 [INFO]      r/android: 4 new posts
2026-05-23 18:17:56,831 [INFO]   -> r/AndroidQuestions
2026-05-23 18:17:57,755 [INFO]      r/AndroidQuestions: 0 new posts
2026-05-23 18:17:59,757 [INFO]   -> r/pickanandroidforme
2026-05-23 18:18:02,681 [INFO]      r/pickanandroidforme: 2 new posts
2026-05-23 18:18:04,683 [INFO]   -> r/budget_phones
2026-05-23 18:18:05,350 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:18:07,353 [INFO]   -> r/technology
2026-05-23 18:18:08,065 [INFO]      r/technology: 3 new posts
2026-05-23 18:18:10,068 [INFO]   -> r/gadgets
2026-05-23 18:18:14,183 [INFO]      r/gadgets: 4 new posts
2026-05-23 18:18:16,186 [INFO]   -> r/hardware
2026-05-23 18:18:16,805 [INFO]      r/hardware: 0 new posts
2026-05-23 18:18:18,807 [INFO]   -> r/nocontract
2026-05-23 18:18:19,710 [INFO]      r/nocontract: 0 new posts
2026-05-23 18:18:23,202 [INFO]   Uploaded 228 records → gs://thesis-bucket-vua/bronze/reddit/galaxy_tab_s2/1779553101.jsonl
2026-05-23 18:18:23,203 [INFO]   Uploaded 228 records for query 'Moto G Fast' -- total: 228
2026-05-23 18:18:28,206 [INFO]
  Query: 'Motorola G Fast'
2026-05-23 18:18:28,207 [INFO]   -> r/motorola
2026-05-23 18:18:29,001 [INFO]      r/motorola: 0 new posts
2026-05-23 18:18:31,003 [INFO]   -> r/Motorola
2026-05-23 18:18:31,548 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:18:33,549 [INFO]   -> r/android
2026-05-23 18:18:34,130 [INFO]      r/android: 0 new posts
2026-05-23 18:18:36,132 [INFO]   -> r/AndroidQuestions
2026-05-23 18:18:37,428 [INFO]      r/AndroidQuestions: 0 new posts
2026-05-23 18:18:39,430 [INFO]   -> r/pickanandroidforme
2026-05-23 18:18:40,065 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:18:42,068 [INFO]   -> r/budget_phones
2026-05-23 18:18:42,631 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:18:44,633 [INFO]   -> r/technology
2026-05-23 18:18:45,171 [INFO]      r/technology: 0 new posts
2026-05-23 18:18:47,174 [INFO]   -> r/gadgets
2026-05-23 18:18:47,969 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:18:49,970 [INFO]   -> r/hardware
2026-05-23 18:18:50,566 [INFO]      r/hardware: 0 new posts
2026-05-23 18:18:52,568 [INFO]   -> r/nocontract
2026-05-23 18:18:53,209 [INFO]      r/nocontract: 0 new posts
2026-05-23 18:19:00,213 [INFO]
  Query: 'moto g fast 2020'
2026-05-23 18:19:00,214 [INFO]   -> r/motorola
2026-05-23 18:19:00,870 [INFO]      r/motorola: 0 new posts
2026-05-23 18:19:02,872 [INFO]   -> r/Motorola
2026-05-23 18:19:03,528 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:19:05,530 [INFO]   -> r/android
2026-05-23 18:19:06,117 [INFO]      r/android: 0 new posts
2026-05-23 18:19:08,119 [INFO]   -> r/AndroidQuestions
2026-05-23 18:19:08,710 [INFO]      r/AndroidQuestions: 0 new posts
2026-05-23 18:19:10,712 [INFO]   -> r/pickanandroidforme
2026-05-23 18:19:11,738 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:19:13,741 [INFO]   -> r/budget_phones
2026-05-23 18:19:14,431 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:19:16,433 [INFO]   -> r/technology
2026-05-23 18:19:16,994 [INFO]      r/technology: 0 new posts
2026-05-23 18:19:18,996 [INFO]   -> r/gadgets
2026-05-23 18:19:19,753 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:19:21,755 [INFO]   -> r/hardware
2026-05-23 18:19:22,486 [INFO]      r/hardware: 0 new posts
2026-05-23 18:19:24,488 [INFO]   -> r/nocontract
2026-05-23 18:19:25,344 [INFO]      r/nocontract: 0 new posts
2026-05-23 18:19:32,347 [INFO]
  Query: 'XT2045'
2026-05-23 18:19:32,348 [INFO]   -> r/motorola
2026-05-23 18:19:32,916 [INFO]      r/motorola: 0 new posts
2026-05-23 18:19:34,918 [INFO]   -> r/Motorola
2026-05-23 18:19:35,604 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:19:37,605 [INFO]   -> r/android
2026-05-23 18:19:38,187 [INFO]      r/android: 0 new posts
2026-05-23 18:19:40,189 [INFO]   -> r/AndroidQuestions
2026-05-23 18:19:41,312 [INFO]      r/AndroidQuestions: 0 new posts
2026-05-23 18:19:43,314 [INFO]   -> r/pickanandroidforme
2026-05-23 18:19:43,895 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:19:45,897 [INFO]   -> r/budget_phones
2026-05-23 18:19:46,897 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:19:48,898 [INFO]   -> r/technology
2026-05-23 18:19:49,466 [INFO]      r/technology: 0 new posts
2026-05-23 18:19:51,468 [INFO]   -> r/gadgets
2026-05-23 18:19:52,052 [INFO]      r/gadgets: 0 new posts
2026-05-23 18:19:54,053 [INFO]   -> r/hardware
2026-05-23 18:19:54,705 [INFO]      r/hardware: 0 new posts
2026-05-23 18:19:56,706 [INFO]   -> r/nocontract
2026-05-23 18:19:57,293 [INFO]      r/nocontract: 0 new posts
2026-05-23 18:20:04,296 [INFO]
  TOTAL: 228 records for galaxy_tab_s2
2026-05-23 18:20:04,298 [WARNING]   WARNING: 228 below threshold of 500
2026-05-23 18:20:14,331 [INFO] Cleared checkpoint for moto_g_3rd_gen
2026-05-23 18:20:14,332 [INFO] Starting targeted scrape: Moto G 3rd Gen
2026-05-23 18:20:14,333 [INFO] Window: 2015-04-29 to 2015-07-28
2026-05-23 18:20:14,335 [INFO]
============================================================
2026-05-23 18:20:14,336 [INFO] Scraping (Arctic Shift): moto_g_fast
2026-05-23 18:20:14,337 [INFO] Window: 2015-04-29 to 2015-07-28
2026-05-23 18:20:14,338 [INFO] Queries: ['Moto G 3rd gen', 'Moto G 2015', 'Motorola Moto G3', 'XT1540', 'XT1541', 'XT1543', 'Moto G3']
2026-05-23 18:20:14,340 [INFO] Subreddits: ['motorola', 'Motorola', 'android', 'AndroidQuestions', 'pickanandroidforme', 'budget_phones', 'technology', 'gadgets', 'hardware', 'nocontract']
2026-05-23 18:20:14,341 [INFO]
  Query: 'Moto G 3rd gen'
2026-05-23 18:20:14,342 [INFO]   -> r/motorola
2026-05-23 18:20:16,531 [INFO]      r/motorola: 7 new posts
2026-05-23 18:20:18,534 [INFO]   -> r/Motorola
2026-05-23 18:20:19,198 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:20:21,200 [INFO]   -> r/android
2026-05-23 18:20:38,561 [INFO]      r/android: 20 new posts
2026-05-23 18:20:40,563 [INFO]   -> r/AndroidQuestions
2026-05-23 18:20:41,134 [INFO]      r/AndroidQuestions: 0 new posts
2026-05-23 18:20:43,137 [INFO]   -> r/pickanandroidforme
2026-05-23 18:20:45,879 [INFO]      r/pickanandroidforme: 2 new posts
2026-05-23 18:20:47,881 [INFO]   -> r/budget_phones
2026-05-23 18:20:48,488 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:20:50,490 [INFO]   -> r/technology
2026-05-23 18:20:51,197 [INFO]      r/technology: 0 new posts
2026-05-23 18:20:53,199 [INFO]   -> r/gadgets
2026-05-23 18:20:57,782 [INFO]      r/gadgets: 6 new posts
2026-05-23 18:20:59,783 [INFO]   -> r/hardware
2026-05-23 18:21:00,438 [INFO]      r/hardware: 0 new posts
2026-05-23 18:21:02,441 [INFO]   -> r/nocontract
2026-05-23 18:21:03,074 [INFO]      r/nocontract: 0 new posts
2026-05-23 18:21:05,206 [INFO]   Uploaded 507 records → gs://thesis-bucket-vua/bronze/reddit/moto_g_fast/1779553265.jsonl
2026-05-23 18:21:05,207 [INFO]   Uploaded 507 records for query 'Moto G 3rd gen' -- total: 507
2026-05-23 18:21:10,209 [INFO]
  Query: 'Moto G 2015'
2026-05-23 18:21:10,210 [INFO]   -> r/motorola
2026-05-23 18:21:10,900 [INFO]      r/motorola: 8 new posts
2026-05-23 18:21:12,902 [INFO]   -> r/Motorola
2026-05-23 18:21:13,652 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:21:15,654 [INFO]   -> r/android
2026-05-23 18:21:49,424 [INFO]      r/android: 39 new posts
2026-05-23 18:21:51,426 [INFO]   -> r/AndroidQuestions
2026-05-23 18:21:53,169 [INFO]      r/AndroidQuestions: 1 new posts
2026-05-23 18:21:55,171 [INFO]   -> r/pickanandroidforme
2026-05-23 18:21:59,072 [INFO]      r/pickanandroidforme: 3 new posts
2026-05-23 18:22:01,073 [INFO]   -> r/budget_phones
2026-05-23 18:22:01,669 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:22:03,671 [INFO]   -> r/technology
2026-05-23 18:22:05,317 [INFO]      r/technology: 2 new posts
2026-05-23 18:22:07,320 [INFO]   -> r/gadgets
2026-05-23 18:22:11,476 [INFO]      r/gadgets: 7 new posts
2026-05-23 18:22:13,479 [INFO]   -> r/hardware
2026-05-23 18:22:14,420 [INFO]      r/hardware: 0 new posts
2026-05-23 18:22:16,422 [INFO]   -> r/nocontract
2026-05-23 18:22:17,031 [INFO]      r/nocontract: 0 new posts
2026-05-23 18:22:19,306 [INFO]   Uploaded 1086 records → gs://thesis-bucket-vua/bronze/reddit/moto_g_fast/1779553339.jsonl
2026-05-23 18:22:19,308 [INFO]   Uploaded 1086 records for query 'Moto G 2015' -- total: 1593
2026-05-23 18:22:24,309 [INFO]
  Query: 'Motorola Moto G3'
2026-05-23 18:22:24,310 [INFO]   -> r/motorola
2026-05-23 18:22:24,841 [INFO]      r/motorola: 0 new posts
2026-05-23 18:22:26,843 [INFO]   -> r/Motorola
2026-05-23 18:22:27,432 [INFO]      r/Motorola: 0 new posts
2026-05-23 18:22:29,434 [INFO]   -> r/android
2026-05-23 18:22:33,419 [INFO]      r/android: 2 new posts
2026-05-23 18:22:35,421 [INFO]   -> r/AndroidQuestions
2026-05-23 18:22:35,960 [INFO]      r/AndroidQuestions: 0 new posts
2026-05-23 18:22:37,962 [INFO]   -> r/pickanandroidforme
2026-05-23 18:22:38,574 [INFO]      r/pickanandroidforme: 0 new posts
2026-05-23 18:22:40,576 [INFO]   -> r/budget_phones
2026-05-23 18:22:41,349 [INFO]      r/budget_phones: 0 new posts
2026-05-23 18:22:43,352 [INFO]   -> r/technology
2026-05-23 18:22:44,121 [INFO]      r/technology: 0 new posts
2026-05-23 18:22:46,122 [INFO]   -> r/gadgets
2026-05-23 18:22:47,019 [INFO]      r/gadgets: 1 new posts
2026-05-23 18:22:49,021 [INFO]   -> r/hardware
2026-05-23 18:22:49,591 [INFO]      r/hardware: 0 new posts
2026-05-23 18:22:51,593 [INFO]   -> r/nocontract

==================================================
Tablets Scrape — Summary
==================================================
  Galaxy Tab S2: 517 records [PASS]
  Moto G Fast: 228 records [FAIL]
  Moto G 3rd Gen: 1693 records [PASS]
  Moto G 4th Gen: 836 records [PASS]

In [89]:
# Full GCS Inventory
all_files = list_bronze_files()
print(f"Total JSONL files in Bronze/Reddit: {len(all_files)}")
print(f"Total size: {all_files['size_kb'].sum():.1f} KB")
display(all_files)

Total JSONL files in Bronze/Reddit: 1396
Total size: 157676.8 KB

,path,size_kb,updated
0,bronze/reddit/acer_chromebook/1779307297.jsonl,3.7,2026-05-20 20:01:39.711000+00:00
1,bronze/reddit/acer_chromebook/1779372807.jsonl,116.2,2026-05-21 14:13:30.775000+00:00
2,bronze/reddit/acer_chromebook/1779372828.jsonl,120.5,2026-05-21 14:13:51.429000+00:00
3,bronze/reddit/acer_chromebook/1779372845.jsonl,107.0,2026-05-21 14:14:08.337000+00:00
4,bronze/reddit/acer_chromebook/1779372866.jsonl,77.3,2026-05-21 14:14:29.055000+00:00
...,...,...,...
1391,bronze/reddit/surface_pro_3/1779376489.jsonl,117.0,2026-05-21 15:14:52.722000+00:00
1392,bronze/reddit/surface_pro_3/1779376555.jsonl,101.4,2026-05-21 15:15:58.379000+00:00
1393,bronze/reddit/surface_pro_3/1779376586.jsonl,108.2,2026-05-21 15:16:29.311000+00:00
1394,bronze/reddit/surface_pro_3/1779376617.jsonl,138.4,2026-05-21 15:17:00.790000+00:00
1395,bronze/reddit/surface_pro_3/1779376625.jsonl,93.3,2026-05-21 15:17:08.837000+00:00

In [67]:
# Run once — clears checkpoint so all events re-scrape
#save_checkpoint({})
# print("✓ Checkpoint cleared")

✓ Checkpoint cleared

In [90]:
# Record count per product event in GCS Bronze
from collections import defaultdict

all_blobs = list(gcs_bucket.list_blobs(prefix=BRONZE_PREFIX))
counts = defaultdict(int)

for blob in all_blobs:
    if not blob.name.endswith(".jsonl"):
        continue
    # Path format: bronze/reddit/{product_event}/{timestamp}.jsonl
    parts = blob.name.split("/")
    if len(parts) >= 3:
        product_event = parts[2]
        # Count lines = count records
        content = blob.download_as_text()
        line_count = len([l for l in content.strip().split("\n") if l])
        counts[product_event] += line_count

summary = pd.DataFrame([
    {
        "product_event": k,
        "records": v,
        "threshold_met": v >= MIN_POST_THRESHOLD
    }
    for k, v in sorted(counts.items(), key=lambda x: x[1], reverse=True)
])

print(f"Total events: {len(summary)}")
print(f"Meeting threshold (>={MIN_POST_THRESHOLD}): {summary['threshold_met'].sum()}")
print()
display(summary)

Total events: 63
Meeting threshold (>=500): 52

                product_event  records  threshold_met
0                     pixel_6    40520           True
1                   iphone_14    33638           True
2                     pixel_5    21426           True
3                    pixel_4a    18273           True
4           ipad_air_2_(2014)    10455           True
..                        ...      ...            ...
58  motorola_g_3rd_generation       72          False
59          galaxy_tab_a_2016       42          False
60        ipad_9th_generation       33          False
61           asus_vivobook_15       22          False
62             fire_7_(2019)_       10          False

[63 rows x 3 columns]

In [64]:
# ── Consolidate duplicate GCS Bronze folders into canonical names ──

# Define canonical name → list of all folder names that should merge into it
consolidation_map = {
    "macbook_air_m1_(2020)": ["macbook_air_m1", "macbook_air_m1_"],
    "fire_hd_8_(2020)":      ["fire_hd_8_(2020)_", "fire_hd_8"],
    "fire_hd_10_(2019)":     ["fire_hd_10_(2019)", "fire_hd_10"],
    "ipad_air_2_(2014)":     ["ipad_air_2", "ipad_air_2_(2014)"],
    "moto_g_4th_gen":      ["moto_g_4th_gen", "moto_g_4th_generation", "moto_g4", "moto_g_4th_gen\""],
    "moto_g_3rd_gen":      ["moto_g_3rd_gen", "moto_g_3rd_generation", "moto_g_2015"],
}

for canonical, sources in consolidation_map.items():
    print(f"\nConsolidating into: {canonical}")
    moved = 0
    deleted = 0

    for source in sources:
        prefix = f"{BRONZE_PREFIX}/{source}/"
        blobs = list(gcs_bucket.list_blobs(prefix=prefix))
        if not blobs:
            print(f"  {source}: no files found")
            continue

        for blob in blobs:
            if not blob.name.endswith(".jsonl"):
                continue

            # Build new path under canonical folder
            filename = blob.name.split("/")[-1]
            new_path = f"{BRONZE_PREFIX}/{canonical}/{source}_{filename}"

            # Copy to canonical folder
            gcs_bucket.copy_blob(blob, gcs_bucket, new_path)
            moved += 1

            # Delete original only if it's not already in the canonical folder
            if source != canonical:
                blob.delete()
                deleted += 1

        print(f"  {source}: moved {len(blobs)} files")

    print(f"  Total moved: {moved}, deleted: {deleted}")

# Verify result
print("\n\nFinal record counts after consolidation:")
from collections import defaultdict
counts = defaultdict(int)
for blob in gcs_bucket.list_blobs(prefix=BRONZE_PREFIX):
    if not blob.name.endswith(".jsonl"):
        continue
    parts = blob.name.split("/")
    if len(parts) >= 3:
        counts[parts[2]] += len(blob.download_as_text().strip().split("\n"))

summary = pd.DataFrame([
    {"product_event": k, "records": v, "threshold_met": v >= MIN_POST_THRESHOLD}
    for k, v in sorted(counts.items(), key=lambda x: x[1], reverse=True)
])
display(summary)

Consolidating into: macbook_air_m1_(2020)
  macbook_air_m1: no files found
  macbook_air_m1_: no files found
  Total moved: 0, deleted: 0

Consolidating into: fire_hd_8_(2020)
  fire_hd_8_(2020)_: no files found
  fire_hd_8: no files found
  Total moved: 0, deleted: 0

Consolidating into: fire_hd_10_(2019)
  fire_hd_10_(2019): moved 81 files
  fire_hd_10: no files found
  Total moved: 81, deleted: 0

Consolidating into: ipad_air_2_(2014)
  ipad_air_2: no files found
  ipad_air_2_(2014): moved 56 files
  Total moved: 56, deleted: 0

Consolidating into: moto_g_4th_gen
  moto_g_4th_gen: moved 8 files
  moto_g_4th_generation: no files found
  moto_g4: moved 4 files
  moto_g_4th_gen": no files found
  Total moved: 12, deleted: 4

Consolidating into: moto_g_3rd_gen
  moto_g_3rd_gen: moved 4 files
  moto_g_3rd_generation: no files found
  moto_g_2015: no files found
  Total moved: 4, deleted: 0


Final record counts after consolidation:

                product_event  records  threshold_met
0                     pixel_6    40520           True
1                   iphone_14    33638           True
2                     pixel_5    21426           True
3           ipad_air_2_(2014)    10455           True
4                   iphone_13     9751           True
..                        ...      ...            ...
57  motorola_g_3rd_generation       72          False
58        ipad_9th_generation       33          False
59           asus_vivobook_15       22          False
60             fire_7_(2019)_       10          False
61          galaxy_tab_a_2016        7          False

[62 rows x 3 columns]